#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/he.xml
# Original file revision: 1.50 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Timbuktu"] = "אפריקה/טימבקטו"
    @exemplarcities["America/Argentina/San_Juan"] = "אמריקה/ארגנטינה/סאן-חואן"
    @exemplarcities["America/Bahia"] = "אמריקה/בהיאה"
    @exemplarcities["America/Buenos_Aires"] = "בואנוס איירס"
    @exemplarcities["America/Cancun"] = "אמריקה/קנקון"
    @exemplarcities["America/Chicago"] = "אמריקה/שיקגו"
    @exemplarcities["America/Cordoba"] = "אמריקה/קורדובה"
    @exemplarcities["America/Dawson_Creek"] = "אמריקה/דוסון-קריק"
    @exemplarcities["America/Denver"] = "אמריקה/דנוור"
    @exemplarcities["America/Detroit"] = "אמריקה/דטרויט"
    @exemplarcities["America/Edmonton"] = "אמריקה/אדמנטון"
    @exemplarcities["America/Halifax"] = "אמריקה/הליפקס"
    @exemplarcities["America/Indianapolis"] = "אינדיאנפוליס"
    @exemplarcities["America/Los_Angeles"] = "אמריקה/לוס-אנג'לס"
    @exemplarcities["America/Louisville"] = "אמריקה/לואיסוויל"
    @exemplarcities["America/Mazatlan"] = "אמריקה/מזטלן"
    @exemplarcities["America/Mendoza"] = "אמריקה/מנדוזה"
    @exemplarcities["America/Mexico_City"] = "אמריקה/מקסיקו סיטי"
    @exemplarcities["America/Monterrey"] = "אמריקה/מונטריי"
    @exemplarcities["America/Montreal"] = "אמריקה/מונטריאול"
    @exemplarcities["America/New_York"] = "אמריקה/ניו-יורק"
    @exemplarcities["America/North_Dakota/Center"] = "אמריקה/צפון דקוטה/מרכז"
    @exemplarcities["America/Phoenix"] = "אמריקה/פיניקס"
    @exemplarcities["America/Santiago"] = "אמריקה/סנטיאגו"
    @exemplarcities["America/Sao_Paulo"] = "אמריקה/סאן-פאולו"
    @exemplarcities["America/Shiprock"] = "אמריקה/שיפרוק"
    @exemplarcities["America/Toronto"] = "אמריקה/טורנטו"
    @exemplarcities["America/Vancouver"] = "אמריקה/ונקובר"
    @exemplarcities["America/Winnipeg"] = "אמריקה/וויניפוג"
    @exemplarcities["Antarctica/Palmer"] = "אמריקה/פאלמר"
    @exemplarcities["Asia/Jakarta"] = "אסיה/ג'קרטה"
    @exemplarcities["Asia/Kuala_Lumpur"] = "קואלה לומפור"
    @exemplarcities["Asia/Novosibirsk"] = "אסיה/נובוסיבירסק"
    @exemplarcities["Asia/Omsk"] = "איה/אומסק"
    @exemplarcities["Asia/Oral"] = "אסיה/אורל"
    @exemplarcities["Asia/Samarkand"] = "אסיה/סמרקנד"
    @exemplarcities["Asia/Shanghai"] = "אסיה/שנחאי"
    @exemplarcities["Asia/Tashkent"] = "אסיה/טשקנט"
    @exemplarcities["Atlantic/Canary"] = "אטלנטי/קנרי"
    @exemplarcities["Australia/Adelaide"] = "אדלייד"
    @exemplarcities["Australia/Brisbane"] = "אוסטרליה/בריסבן"
    @exemplarcities["Australia/Broken_Hill"] = "אוסטרליה/ברוקן-היל"
    @exemplarcities["Australia/Darwin"] = "אוסטרליה/דרווין"
    @exemplarcities["Australia/Hobart"] = "אוסטרליה/הוברט"
    @exemplarcities["Australia/Melbourne"] = "אוסטרליה/מלבורן"
    @exemplarcities["Australia/Perth"] = "אוסטרליה/פרת'"
    @exemplarcities["Australia/Sydney"] = "אוסטרליה/סידני"
    @exemplarcities["Europe/Belfast"] = "אירופה/בלפסט"
    @exemplarcities["Europe/Kiev"] = "אירופה/קייב"
    @exemplarcities["Europe/Lisbon"] = "אירופה/ליסבון"
    @exemplarcities["Europe/London"] = "אירופה/לונדון"
    @exemplarcities["Europe/Madrid"] = "אירופה/מדריד"
    @exemplarcities["Europe/Moscow"] = "אירופה/מוסקבה"
    @exemplarcities["Europe/Samara"] = "אירופה/סמרה"
    @exemplarcities["Pacific/Auckland"] = "פסיפי/אוקלנד"
    @exemplarcities["Pacific/Galapagos"] = "פסיפי/גלאפגוס"
    @exemplarcities["Pacific/Honolulu"] = "פסיפי/הונולולו"
    @exemplarcities["Pacific/Tahiti"] = "פסיפי/טהיטי"
    @long_generics = {}
    @long_standards = {}
    @long_daylights = {}
    @short_generics = {}
    @short_standards = {}
    @short_daylights = {}
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
