#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/it_CH.xml
# Original file revision: 1.25 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Casablanca"] = "Casablanca"
    @exemplarcities["Africa/Timbuktu"] = "Timbuctu"
    @exemplarcities["America/Cordoba"] = "Cordova"
    @exemplarcities["America/Mexico_City"] = "Città del Messico"
    @exemplarcities["America/Sao_Paulo"] = "San Paolo"
    @exemplarcities["America/St_Johns"] = "St. Johns"
    @exemplarcities["Antarctica/South_Pole"] = "Polo Sud"
    @exemplarcities["Asia/Jakarta"] = "Giacarta"
    @exemplarcities["Asia/Jerusalem"] = "Gerusalemme"
    @exemplarcities["Asia/Samarkand"] = "Samarcanda"
    @exemplarcities["Asia/Tokyo"] = "Tokyo"
    @exemplarcities["Atlantic/Azores"] = "Azzorre"
    @exemplarcities["Atlantic/Canary"] = "Canarie"
    @exemplarcities["Europe/Bucharest"] = "Bucarest"
    @exemplarcities["Europe/Lisbon"] = "Lisbona"
    @exemplarcities["Europe/London"] = "Londra"
    @exemplarcities["Europe/Moscow"] = "Mosca"
    @exemplarcities["Europe/Paris"] = "Parigi"
    @exemplarcities["Pacific/Easter"] = "Pasqua"
    @long_generics = {}
    @long_standards = {}
    @long_standards["Africa/Casablanca"] = "Ora Meridiano Greenwich"
    @long_standards["America/Anchorage"] = "Ora Standard Alaska"
    @long_standards["America/Chicago"] = "Ora Standard Centrale"
    @long_standards["America/Denver"] = "Ora Standard Mountain"
    @long_standards["America/Halifax"] = "Ora Standard Atlantico"
    @long_standards["America/Indianapolis"] = "Ora Standard Orientale"
    @long_standards["America/Los_Angeles"] = "Ora Standard Pacifico"
    @long_standards["America/New_York"] = "Ora Standard Orientale"
    @long_standards["America/Phoenix"] = "Ora Standard Mountain"
    @long_standards["America/St_Johns"] = "Ora Standard Newfoundland"
    @long_standards["Asia/Jerusalem"] = "Ora Standard Israele"
    @long_standards["Asia/Shanghai"] = "Ora Standard Cina"
    @long_standards["Asia/Tokyo"] = "Ora Standard Giappone"
    @long_standards["Europe/Bucharest"] = "Ora Standard Europa Orientale"
    @long_standards["Europe/Paris"] = "Ora Standard Centrale Europeo"
    @long_standards["Pacific/Honolulu"] = "Ora Standard Hawaii"
    @long_daylights = {}
    @long_daylights["Africa/Casablanca"] = "Ora Meridiano Greenwich"
    @long_daylights["America/Anchorage"] = "Ora Legale Alaska"
    @long_daylights["America/Chicago"] = "Ora Legale Centrale"
    @long_daylights["America/Denver"] = "Ora Legale Mountain"
    @long_daylights["America/Halifax"] = "Ora Legale Atlantico"
    @long_daylights["America/Indianapolis"] = "Ora Standard Orientale"
    @long_daylights["America/Los_Angeles"] = "Ora Legale Pacifico"
    @long_daylights["America/New_York"] = "Ora Legale Orientale"
    @long_daylights["America/Phoenix"] = "Ora Standard Mountain"
    @long_daylights["America/St_Johns"] = "Ora Legale Newfoundland"
    @long_daylights["Asia/Jerusalem"] = "Ora Legale Israele"
    @long_daylights["Asia/Shanghai"] = "Ora Standard Cina"
    @long_daylights["Asia/Tokyo"] = "Ora Standard Giappone"
    @long_daylights["Europe/Bucharest"] = "Ora Legale Europa Orientale"
    @long_daylights["Europe/Paris"] = "Ora Legale Centrale Europeo"
    @long_daylights["Pacific/Honolulu"] = "Ora Standard Hawaii"
    @short_generics = {}
    @short_standards = {}
    @short_standards["Africa/Casablanca"] = "GMT"
    @short_standards["America/Anchorage"] = "AST"
    @short_standards["America/Chicago"] = "CST"
    @short_standards["America/Denver"] = "MST"
    @short_standards["America/Halifax"] = "AST"
    @short_standards["America/Indianapolis"] = "EST"
    @short_standards["America/Los_Angeles"] = "PST"
    @short_standards["America/New_York"] = "EST"
    @short_standards["America/Phoenix"] = "MST"
    @short_standards["America/St_Johns"] = "CNT"
    @short_standards["Asia/Jerusalem"] = "IST"
    @short_standards["Asia/Shanghai"] = "CTT"
    @short_standards["Asia/Tokyo"] = "JST"
    @short_standards["Europe/Bucharest"] = "EET"
    @short_standards["Europe/Paris"] = "CET"
    @short_standards["Pacific/Honolulu"] = "HST"
    @short_daylights = {}
    @short_daylights["Africa/Casablanca"] = "GMT"
    @short_daylights["America/Anchorage"] = "ADT"
    @short_daylights["America/Chicago"] = "CDT"
    @short_daylights["America/Denver"] = "MDT"
    @short_daylights["America/Halifax"] = "ADT"
    @short_daylights["America/Indianapolis"] = "EST"
    @short_daylights["America/Los_Angeles"] = "PDT"
    @short_daylights["America/New_York"] = "EDT"
    @short_daylights["America/Phoenix"] = "MST"
    @short_daylights["America/St_Johns"] = "CDT"
    @short_daylights["Asia/Jerusalem"] = "IDT"
    @short_daylights["Asia/Shanghai"] = "CDT"
    @short_daylights["Asia/Tokyo"] = "JST"
    @short_daylights["Europe/Bucharest"] = "EEST"
    @short_daylights["Europe/Paris"] = "CEST"
    @short_daylights["Pacific/Honolulu"] = "HST"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
