#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/sw.xml
# Original file revision: 1.32 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["sw"] = "Kiswahili"
    @territories = {}
    @territories["AE"] = "Muugano wa Falme za Nchi za Kiarabu"
    @territories["AG"] = "Antigua na Barbuda"
    @territories["AR"] = "Ajentina"
    @territories["BA"] = "Bosnia na Herzegowina"
    @territories["BE"] = "Ubelgiji"
    @territories["BR"] = "Brazili"
    @territories["BS"] = "Visiwa vya Bahama"
    @territories["CA"] = "Kanada"
    @territories["CF"] = "Jamhuri ya Afrika ya Kati"
    @territories["CG"] = "Kongo"
    @territories["CH"] = "Uswisi"
    @territories["CI"] = "Pwani ya Pembe"
    @territories["CM"] = "Kamerun"
    @territories["CN"] = "Uchina"
    @territories["CO"] = "Kolombia"
    @territories["CS"] = "Serbiya da Montenegro"
    @territories["CV"] = "Rasi Verde"
    @territories["CZ"] = "Jamhuri ya Czech"
    @territories["DE"] = "Udachi"
    @territories["DJ"] = "Jibuti"
    @territories["DK"] = "Udenmarki"
    @territories["DM"] = "Dominika"
    @territories["DO"] = "Jamhuri ya Dominikan"
    @territories["EC"] = "Ekvado"
    @territories["EG"] = "Misri"
    @territories["ES"] = "Uhispania"
    @territories["ET"] = "Uhabeshi"
    @territories["FR"] = "Ufaransa"
    @territories["GB"] = "Uingereza"
    @territories["GQ"] = "Guinea ya Ikweta"
    @territories["HR"] = "Kroatia"
    @territories["HU"] = "Hungaria"
    @territories["IL"] = "Uyahudi"
    @territories["IN"] = "Uhindi"
    @territories["IQ"] = "Iraki"
    @territories["IR"] = "Uajemi"
    @territories["IS"] = "Barafu"
    @territories["IT"] = "Uitaliani"
    @territories["JM"] = "Jamaika"
    @territories["JP"] = "Ujapani"
    @territories["KE"] = "Kenya"
    @territories["KH"] = "Kampuchea"
    @territories["KM"] = "Visiwa vya Komoro"
    @territories["KN"] = "Saint Kitts na Nevis"
    @territories["KP"] = "Korea ya Kaskazini"
    @territories["KR"] = "Korea ya Kusini"
    @territories["LU"] = "Luksemburg"
    @territories["MA"] = "Moroko"
    @territories["MC"] = "Monako"
    @territories["MH"] = "Visiwa vya Marshall"
    @territories["MX"] = "Meksiko"
    @territories["MY"] = "Malasya"
    @territories["MZ"] = "Msumbiji"
    @territories["NI"] = "Nikaragua"
    @territories["NL"] = "Uholanzi"
    @territories["NO"] = "Unorwe"
    @territories["NP"] = "Nepali"
    @territories["PG"] = "Papua Guinea Mpya"
    @territories["PH"] = "Filipino"
    @territories["PT"] = "Ureno"
    @territories["PY"] = "Paragwai"
    @territories["RU"] = "Urusi"
    @territories["SA"] = "Arabuni Saudi"
    @territories["SB"] = "Visiwa vya Solomon"
    @territories["SC"] = "Visiwa vya Shelisheli"
    @territories["SE"] = "Uswidi"
    @territories["SO"] = "Somali"
    @territories["ST"] = "Sao Tome na Principe"
    @territories["TD"] = "Chadi"
    @territories["TL"] = "Timor ya Mashariki"
    @territories["TR"] = "Uturuki"
    @territories["TT"] = "Trinidad na Tobago"
    @territories["TZ"] = "Tanzania"
    @territories["US"] = "Muungano wa Nchi za Amerika"
    @territories["UY"] = "Urugwai"
    @territories["VA"] = "Vatikano"
    @territories["VC"] = "Saint Vincent na Grenadines"
    @territories["YE"] = "Yemeni"
    @territories["ZA"] = "Afrika ya Kusini"
    @scripts = {}
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[a-z]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
