#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/sv_FI.xml
# Original file revision: 1.27 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH.mm;-HH.mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Casablanca"] = "Casablanca"
    @exemplarcities["America/Argentina/ComodRivadavia"] = "Comod. Rivadavia"
    @exemplarcities["America/Argentina/Rio_Gallegos"] = " Rio Gallegos"
    @exemplarcities["America/Godthab"] = "Godthåb"
    @exemplarcities["America/North_Dakota/Center"] = "North Dakota"
    @exemplarcities["America/Sao_Paulo"] = "São Paulo"
    @exemplarcities["America/St_Johns"] = "St. Johns"
    @exemplarcities["Antarctica/DumontDUrville"] = "Dumont d'Urville"
    @exemplarcities["Antarctica/South_Pole"] = "Sydpolen"
    @exemplarcities["Asia/Almaty"] = "Alma-Ata"
    @exemplarcities["Asia/Anadyr"] = "Anadir"
    @exemplarcities["Asia/Choibalsan"] = "Tjoibalsan"
    @exemplarcities["Asia/Jerusalem"] = "Jerusalem"
    @exemplarcities["Asia/Kamchatka"] = "Kamtjatka"
    @exemplarcities["Asia/Krasnoyarsk"] = "Krasnojarsk"
    @exemplarcities["Asia/Sakhalin"] = "Sachalin"
    @exemplarcities["Asia/Tashkent"] = "Tasjkent"
    @exemplarcities["Asia/Tokyo"] = "Tokyo"
    @exemplarcities["Asia/Ulaanbaatar"] = "Ulan Bator"
    @exemplarcities["Asia/Yakutsk"] = "Jakutsk"
    @exemplarcities["Asia/Yekaterinburg"] = "Jekaterinburg"
    @exemplarcities["Atlantic/Azores"] = "Azorerna"
    @exemplarcities["Atlantic/Canary"] = "Kanarieöarna"
    @exemplarcities["Europe/Bucharest"] = "Bukarest"
    @exemplarcities["Europe/Lisbon"] = "Lissabon"
    @exemplarcities["Europe/Moscow"] = "Moskva"
    @exemplarcities["Europe/Paris"] = "Paris"
    @exemplarcities["Europe/Uzhgorod"] = "Uzjgorod"
    @exemplarcities["Europe/Zaporozhye"] = "Zaporozjzja"
    @exemplarcities["Pacific/Easter"] = "Påskön"
    @long_generics = {}
    @long_standards = {}
    @long_standards["Africa/Casablanca"] = "Greenwichtid"
    @long_standards["America/Anchorage"] = "Alaska, normaltid"
    @long_standards["America/Chicago"] = "Central, normaltid"
    @long_standards["America/Denver"] = "Mountain, normaltid"
    @long_standards["America/Halifax"] = "Atlantic, normaltid"
    @long_standards["America/Indianapolis"] = "Eastern, normaltid"
    @long_standards["America/Los_Angeles"] = "Pacific, normaltid"
    @long_standards["America/New_York"] = "Eastern, normaltid"
    @long_standards["America/Phoenix"] = "Mountain, normaltid"
    @long_standards["America/St_Johns"] = "Newfoundland, normaltid"
    @long_standards["Asia/Jerusalem"] = "Israel, normaltid"
    @long_standards["Asia/Shanghai"] = "Kina, normaltid"
    @long_standards["Asia/Tokyo"] = "Japan, normaltid"
    @long_standards["Europe/Bucharest"] = "Östeuropa, normaltid"
    @long_standards["Europe/Paris"] = "Centraleuropa, normaltid"
    @long_standards["Pacific/Honolulu"] = "Hawaii, normaltid"
    @long_daylights = {}
    @long_daylights["Africa/Casablanca"] = "Greenwichtid"
    @long_daylights["America/Anchorage"] = "Alaska, sommartid"
    @long_daylights["America/Chicago"] = "Central, sommartid"
    @long_daylights["America/Denver"] = "Mountain, sommartid"
    @long_daylights["America/Halifax"] = "Atlantic, sommartid"
    @long_daylights["America/Indianapolis"] = "Eastern, normaltid"
    @long_daylights["America/Los_Angeles"] = "Pacific, sommartid"
    @long_daylights["America/New_York"] = "Eastern, sommartid"
    @long_daylights["America/Phoenix"] = "Mountain, sommartid"
    @long_daylights["America/St_Johns"] = "Newfoundland, sommartid"
    @long_daylights["Asia/Jerusalem"] = "Israel, sommartid"
    @long_daylights["Asia/Shanghai"] = "Kina, normaltid"
    @long_daylights["Asia/Tokyo"] = "Japan, normaltid"
    @long_daylights["Europe/Bucharest"] = "Östeuropa, sommartid"
    @long_daylights["Europe/Paris"] = "Centraleuropa, sommartid"
    @long_daylights["Pacific/Honolulu"] = "Hawaii, normaltid"
    @short_generics = {}
    @short_standards = {}
    @short_standards["Africa/Casablanca"] = "GMT"
    @short_standards["America/Anchorage"] = "AST"
    @short_standards["America/Chicago"] = "CST"
    @short_standards["America/Denver"] = "MST"
    @short_standards["America/Halifax"] = "AST"
    @short_standards["America/Indianapolis"] = "EST"
    @short_standards["America/Los_Angeles"] = "PST"
    @short_standards["America/New_York"] = "EST"
    @short_standards["America/Phoenix"] = "MST"
    @short_standards["America/St_Johns"] = "CNT"
    @short_standards["Asia/Jerusalem"] = "IST"
    @short_standards["Asia/Shanghai"] = "CTT"
    @short_standards["Asia/Tokyo"] = "JST"
    @short_standards["Europe/Bucharest"] = "EET"
    @short_standards["Europe/Paris"] = "CET"
    @short_standards["Pacific/Honolulu"] = "HST"
    @short_daylights = {}
    @short_daylights["Africa/Casablanca"] = "GMT"
    @short_daylights["America/Anchorage"] = "ADT"
    @short_daylights["America/Chicago"] = "CDT"
    @short_daylights["America/Denver"] = "MDT"
    @short_daylights["America/Halifax"] = "ADT"
    @short_daylights["America/Indianapolis"] = "EST"
    @short_daylights["America/Los_Angeles"] = "PDT"
    @short_daylights["America/New_York"] = "EDT"
    @short_daylights["America/Phoenix"] = "MST"
    @short_daylights["America/St_Johns"] = "CDT"
    @short_daylights["Asia/Jerusalem"] = "IDT"
    @short_daylights["Asia/Shanghai"] = "CDT"
    @short_daylights["Asia/Tokyo"] = "JST"
    @short_daylights["Europe/Bucharest"] = "EEST"
    @short_daylights["Europe/Paris"] = "CEST"
    @short_daylights["Pacific/Honolulu"] = "HST"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
