#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/sq_AL.xml
# Original file revision: 1.25 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["ar"] = "Arabisht"
    @languages["de"] = "Gjermanisht"
    @languages["en"] = "Anglisht"
    @languages["es"] = "Spanjisht"
    @languages["fr"] = "Frengjisht"
    @languages["hi"] = "Hindi"
    @languages["it"] = "Italisht"
    @languages["ja"] = "Japanisht"
    @languages["pt"] = "Portugeze"
    @languages["ru"] = "Rusisht"
    @languages["sq"] = "shqipe"
    @languages["zh"] = "Kineze"
    @territories = {}
    @territories["AD"] = "Andorrë"
    @territories["AE"] = "Emiratet Arabe te Bashkuara"
    @territories["AF"] = "Afganistan"
    @territories["AG"] = "Antigua e Barbuda"
    @territories["AL"] = "Shqipëria"
    @territories["AM"] = "Armeni"
    @territories["AO"] = "Angolë"
    @territories["AR"] = "Argjentinë"
    @territories["AT"] = "Austri"
    @territories["AU"] = "Australi"
    @territories["AZ"] = "Azerbajxhan"
    @territories["BA"] = "Bosnja dhe Hercegovina"
    @territories["BE"] = "Belgjikë"
    @territories["BG"] = "Bullgari"
    @territories["BH"] = "Bahrein"
    @territories["BN"] = "Brunej"
    @territories["BO"] = "Bolivi"
    @territories["BR"] = "Brazili"
    @territories["BT"] = "Butan"
    @territories["BW"] = "Botsvana"
    @territories["BY"] = "Bjellorusi"
    @territories["CA"] = "Kanada"
    @territories["CF"] = "Republika Qendrore e Afrikës"
    @territories["CG"] = "Kongo"
    @territories["CH"] = "Zvicër"
    @territories["CI"] = "Bregu i Fildishtë"
    @territories["CL"] = "Kili"
    @territories["CM"] = "Kamerun"
    @territories["CN"] = "Kinë"
    @territories["CO"] = "Kolumbi"
    @territories["CR"] = "Kosta Rika"
    @territories["CS"] = "Serbië en Montenegro"
    @territories["CU"] = "Kubë"
    @territories["CV"] = "Kap Verde"
    @territories["CY"] = "Qipro"
    @territories["CZ"] = "Republika e Çekisë"
    @territories["DE"] = "Gjermani"
    @territories["DJ"] = "Xhibuti"
    @territories["DK"] = "Danimarkë"
    @territories["DM"] = "Dominikë"
    @territories["DO"] = "Republika Dominikanë"
    @territories["DZ"] = "Algjeri"
    @territories["EC"] = "Ekuator"
    @territories["EE"] = "Estoni"
    @territories["EG"] = "Egjipt"
    @territories["EH"] = "Saharaja Perëndimore"
    @territories["ER"] = "Eritre"
    @territories["ES"] = "Spanjë"
    @territories["ET"] = "Etiopi"
    @territories["FI"] = "Finlandë"
    @territories["FJ"] = "Fixhi"
    @territories["FM"] = "Mikronezi"
    @territories["FR"] = "Francë"
    @territories["GA"] = "Gjabon"
    @territories["GB"] = "Mbretëria e Bashkuar"
    @territories["GE"] = "Gjeorgji"
    @territories["GH"] = "Ganë"
    @territories["GM"] = "Gambi"
    @territories["GN"] = "Guine"
    @territories["GQ"] = "Guineja Ekuatoriale"
    @territories["GR"] = "Greqi"
    @territories["GT"] = "Guatemalë"
    @territories["GW"] = "Guine Bisau"
    @territories["GY"] = "Guajana"
    @territories["HR"] = "Kroaci"
    @territories["HU"] = "Hungari"
    @territories["ID"] = "Indonezi"
    @territories["IE"] = "Irlandë"
    @territories["IL"] = "Izrael"
    @territories["IN"] = "Indi"
    @territories["IQ"] = "Irak"
    @territories["IS"] = "Islandë"
    @territories["IT"] = "Itali"
    @territories["JM"] = "Xhamajkë"
    @territories["JO"] = "Jordani"
    @territories["JP"] = "Japoni"
    @territories["KE"] = "Kenia"
    @territories["KG"] = "Kirgistan"
    @territories["KH"] = "Kamboxhi"
    @territories["KI"] = "Qiribati"
    @territories["KM"] = "Komore"
    @territories["KN"] = "Saint Kitts e Nevis"
    @territories["KP"] = "Koreja e Veriut"
    @territories["KR"] = "Koreja e Jugut"
    @territories["KW"] = "Kuvajt"
    @territories["KZ"] = "Kazakistan"
    @territories["LB"] = "Liban"
    @territories["LI"] = "Lihtënshtajn"
    @territories["LR"] = "Liberi"
    @territories["LS"] = "Lesoto"
    @territories["LT"] = "Lituani"
    @territories["LU"] = "Luksemburg"
    @territories["LV"] = "Letoni"
    @territories["LY"] = "Libi"
    @territories["MA"] = "Maroko"
    @territories["MC"] = "Monako"
    @territories["MD"] = "Moldavi"
    @territories["MG"] = "Madagaskar"
    @territories["MH"] = "Ishujt Marshall"
    @territories["MK"] = "Maqedoni"
    @territories["MN"] = "Mongoli"
    @territories["MR"] = "Mauritani"
    @territories["MT"] = "Maltë"
    @territories["MV"] = "Maldivit"
    @territories["MW"] = "Malavi"
    @territories["MX"] = "Meksikë"
    @territories["MY"] = "Malajzi"
    @territories["MZ"] = "Mozambik"
    @territories["NA"] = "Namibi"
    @territories["NG"] = "Nigeri"
    @territories["NI"] = "Nikaragua"
    @territories["NL"] = "Vendet e Ulëta"
    @territories["NO"] = "Norvegji"
    @territories["NZ"] = "Zelanda e Re"
    @territories["PG"] = "Papua Guineja e Re"
    @territories["PH"] = "Filipine"
    @territories["PL"] = "Poloni"
    @territories["PT"] = "Portugali"
    @territories["PY"] = "Paraguaj"
    @territories["QA"] = "Katar"
    @territories["RO"] = "Rumani"
    @territories["RU"] = "Rusi"
    @territories["RW"] = "Ruanda"
    @territories["SA"] = "Arabia Saudite"
    @territories["SB"] = "Ishujt Solomon"
    @territories["SC"] = "Sishel"
    @territories["SE"] = "Suedi"
    @territories["SG"] = "Singapor"
    @territories["SI"] = "Slloveni"
    @territories["SK"] = "Sllovaki"
    @territories["SL"] = "Siera Leone"
    @territories["SO"] = "Somali"
    @territories["ST"] = "Sao Tome e Prinsipe"
    @territories["SY"] = "Siri"
    @territories["SZ"] = "Svazilandë"
    @territories["TD"] = "Çad"
    @territories["TG"] = "Togo"
    @territories["TH"] = "Tajlandë"
    @territories["TJ"] = "Taxhikistan"
    @territories["TN"] = "Tunisi"
    @territories["TR"] = "Turqi"
    @territories["TT"] = "Trinidad e Tobago"
    @territories["TW"] = "Tajvan"
    @territories["TZ"] = "Tanzani"
    @territories["UA"] = "Ukrainë"
    @territories["US"] = "Shtetet e Bashkuara të Amerikës"
    @territories["UY"] = "Uruguaj"
    @territories["VA"] = "Vatikan"
    @territories["VC"] = "Saint Vincent e Grenadinet"
    @territories["VE"] = "Venezuelë"
    @territories["YE"] = "Jemen"
    @territories["ZA"] = "Afrika e Jugut"
    @territories["ZM"] = "Zambi"
    @territories["ZW"] = "Zimbabve"
    @scripts = {}
    @scripts["Latn"] = "Latine"
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[a-zçë{dh}{gj}{ll}{nj}{rr}{sh}{th}{xh}{zh}]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "po:p"
    @nostr = "jo:j"
    @yesexpr = "^([yY]([eE][sS])?)|([pP][oO]?)"
    @noexpr = "^[nNjJ][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
