#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/eu.xml
# Original file revision: 1.36 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["eu"] = "euskara"
    @territories = {}
    @territories["AE"] = "Arabiar Emirrerri Batuak"
    @territories["AF"] = "Afganistan"
    @territories["AG"] = "Antigua eta Barbuda"
    @territories["AQ"] = "Antartika"
    @territories["BA"] = "Bosnia-Herzegovina"
    @territories["BE"] = "Belgika"
    @territories["BO"] = "Bolibia"
    @territories["BR"] = "Brasil"
    @territories["BS"] = "Bahamak"
    @territories["BY"] = "Bielorrusia"
    @territories["CA"] = "Kanada"
    @territories["CF"] = "Afrika Erdiko Errepublika"
    @territories["CG"] = "Kongo"
    @territories["CH"] = "Suitza"
    @territories["CI"] = "Boli Kosta"
    @territories["CL"] = "Txile"
    @territories["CM"] = "Kamerun"
    @territories["CN"] = "Txina"
    @territories["CO"] = "Kolonbia"
    @territories["CS"] = "Serbia eta Montenegro"
    @territories["CU"] = "Kuba"
    @territories["CV"] = "Cabo Verde"
    @territories["CY"] = "Zipre"
    @territories["CZ"] = "Txekiar errepublika"
    @territories["DE"] = "Alemania"
    @territories["DJ"] = "Djibuti"
    @territories["DK"] = "Danimarka"
    @territories["DM"] = "Dominika"
    @territories["DO"] = "Dominikar Errepublika"
    @territories["DZ"] = "Aljeria"
    @territories["EC"] = "Ekuador"
    @territories["EG"] = "Egipto"
    @territories["EH"] = "Mendebaldeko Sahara"
    @territories["ES"] = "Espainia"
    @territories["ET"] = "Etiopia"
    @territories["FI"] = "Finlandia"
    @territories["FM"] = "Mikronesia"
    @territories["FR"] = "Frantzia"
    @territories["GN"] = "Ginea"
    @territories["GQ"] = "Ekuatore Ginea"
    @territories["GR"] = "Grezia"
    @territories["GW"] = "Ginea-Bissau"
    @territories["HR"] = "Kroazia"
    @territories["HU"] = "Hungaria"
    @territories["IE"] = "Irlanda"
    @territories["IQ"] = "Irak"
    @territories["IS"] = "Islandia"
    @territories["IT"] = "Italia"
    @territories["JM"] = "Jamaika"
    @territories["JO"] = "Jordania"
    @territories["JP"] = "Japonia"
    @territories["KE"] = "Kenia"
    @territories["KG"] = "Kirgizistan"
    @territories["KH"] = "Kanbodia"
    @territories["KM"] = "Komoreak"
    @territories["KN"] = "Saint Kitts eta Nevis"
    @territories["KP"] = "Ipar Korea"
    @territories["KR"] = "Hego Korea"
    @territories["LB"] = "Libano"
    @territories["LC"] = "Santa Luzia"
    @territories["LT"] = "Lituania"
    @territories["LU"] = "Luxenburgo"
    @territories["LV"] = "Letonia"
    @territories["LY"] = "Libia"
    @territories["MA"] = "Maroko"
    @territories["MC"] = "Monako"
    @territories["MD"] = "Moldavia"
    @territories["MG"] = "Madagaskar"
    @territories["MH"] = "Marshall uharteak"
    @territories["MK"] = "Mazedonia"
    @territories["MU"] = "Maurizio"
    @territories["MV"] = "Maldivak"
    @territories["MX"] = "Mexiko"
    @territories["MY"] = "Malasia"
    @territories["MZ"] = "Mozambike"
    @territories["NI"] = "Nikaragua"
    @territories["NL"] = "Herbehereak"
    @territories["NO"] = "Norvegia"
    @territories["NZ"] = "Zeelanda Berria"
    @territories["PG"] = "Papua Ginea Berria"
    @territories["PH"] = "Filipinak"
    @territories["PL"] = "Polonia"
    @territories["PY"] = "Paraguai"
    @territories["QA"] = "Katar"
    @territories["RO"] = "Errumania"
    @territories["RU"] = "Errusia"
    @territories["RW"] = "Ruanda"
    @territories["SB"] = "Salomon uharteak"
    @territories["SC"] = "Seychelleak"
    @territories["SE"] = "Suedia"
    @territories["SG"] = "Singapur"
    @territories["SI"] = "Eslovenia"
    @territories["SK"] = "Eslovakia"
    @territories["SL"] = "Sierra Leona"
    @territories["SR"] = "Surinam"
    @territories["ST"] = "Sao Tomé eta Principe"
    @territories["SY"] = "Siria"
    @territories["SZ"] = "Swazilandia"
    @territories["TD"] = "Txad"
    @territories["TH"] = "Tailandia"
    @territories["TJ"] = "Tadjikistan"
    @territories["TR"] = "Turkia"
    @territories["TT"] = "Trinidad eta Tobago"
    @territories["UA"] = "Ukraina"
    @territories["US"] = "Ameriketako Estatu Batuak"
    @territories["UY"] = "Uruguai"
    @territories["VA"] = "Vatikano"
    @territories["VC"] = "Saint Vincent eta Grenadinak"
    @territories["ZA"] = "Hegoafrika"
    @scripts = {}
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[a-zñç]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "‘"
    @delimiter_quotation_end = "’"
    @delimiter_alternate_quotation_start = "“"
    @delimiter_alternate_quotation_end = "”"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
