#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/fi.xml
# Original file revision: 1.55 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Casablanca"] = "Casablanca"
    @exemplarcities["America/Argentina/ComodRivadavia"] = "Comodoro Rivadavia"
    @exemplarcities["America/Cancun"] = "Cancún"
    @exemplarcities["America/North_Dakota/Center"] = "keskinen North Dakota"
    @exemplarcities["America/Sao_Paulo"] = "São Paulo"
    @exemplarcities["America/St_Johns"] = "St. Johns"
    @exemplarcities["Antarctica/DumontDUrville"] = "Dumont d'Urville"
    @exemplarcities["Antarctica/South_Pole"] = "Etelänapa"
    @exemplarcities["Asia/Jerusalem"] = "Jerusalem"
    @exemplarcities["Asia/Kamchatka"] = "Kamtšatka"
    @exemplarcities["Asia/Krasnoyarsk"] = "Krasnojarsk"
    @exemplarcities["Asia/Sakhalin"] = "Sahalin"
    @exemplarcities["Asia/Tashkent"] = "Taškent"
    @exemplarcities["Asia/Tokyo"] = "Tokio"
    @exemplarcities["Asia/Ulaanbaatar"] = "Ulan Bator"
    @exemplarcities["Asia/Yakutsk"] = "Jakutsk"
    @exemplarcities["Asia/Yekaterinburg"] = "Jekaterinburg"
    @exemplarcities["Atlantic/Azores"] = "Azorit"
    @exemplarcities["Atlantic/Canary"] = "Kanariansaaret"
    @exemplarcities["Europe/Bucharest"] = "Bukarest"
    @exemplarcities["Europe/Kiev"] = "Kiova"
    @exemplarcities["Europe/Lisbon"] = "Lissabon"
    @exemplarcities["Europe/London"] = "Lontoo"
    @exemplarcities["Europe/Moscow"] = "Moskova"
    @exemplarcities["Europe/Paris"] = "Pariisi"
    @exemplarcities["Europe/Uzhgorod"] = "Užgorod"
    @exemplarcities["Pacific/Easter"] = "Pääsiäissaari"
    @long_generics = {}
    @long_standards = {}
    @long_standards["Africa/Casablanca"] = "Greenwichin aika"
    @long_standards["America/Anchorage"] = "Alaskan normaaliaika"
    @long_standards["America/Chicago"] = "Yhdysvaltain keskinen normaaliaika>"
    @long_standards["America/Denver"] = "Kalliovuorten normaaliaika"
    @long_standards["America/Halifax"] = "Kanadan Atlantin normaaliaika"
    @long_standards["America/Indianapolis"] = "Yhdysvaltain itäinen normaaliaika"
    @long_standards["America/Los_Angeles"] = "Yhdysvaltain Tyynenmeren normaaliaika"
    @long_standards["America/New_York"] = "Yhdysvaltain itäinen normaaliaika"
    @long_standards["America/Phoenix"] = "Kalliovuorten normaaliaika"
    @long_standards["America/St_Johns"] = "Newfoundlandin normaaliaika"
    @long_standards["Asia/Jerusalem"] = "Israelin normaaliaika"
    @long_standards["Asia/Shanghai"] = "Kiinan normaaliaika"
    @long_standards["Asia/Tokyo"] = "Japanin normaaliaika"
    @long_standards["Europe/Bucharest"] = "Itä-Euroopan normaaliaika"
    @long_standards["Europe/Paris"] = "Keski-Euroopan normaaliaika"
    @long_standards["Pacific/Honolulu"] = "Havaijin normaaliaika"
    @long_daylights = {}
    @long_daylights["Africa/Casablanca"] = "Greenwichin aika"
    @long_daylights["America/Anchorage"] = "Alaskan kesäaika"
    @long_daylights["America/Chicago"] = "Yhdysvaltain keskinen kesäaika"
    @long_daylights["America/Denver"] = "Kalliovuorten kesäaika"
    @long_daylights["America/Halifax"] = "Kanadan Atlantin kesäaika"
    @long_daylights["America/Indianapolis"] = "Yhdysvaltain itäinen normaaliaika"
    @long_daylights["America/Los_Angeles"] = "Yhdysvaltain Tyynenmeren kesäaika"
    @long_daylights["America/New_York"] = "Yhdysvaltain itäinen kesäaika"
    @long_daylights["America/Phoenix"] = "Kalliovuorten normaaliaika"
    @long_daylights["America/St_Johns"] = "Newfoundlandin kesäaika"
    @long_daylights["Asia/Jerusalem"] = "Israelin kesäaika"
    @long_daylights["Asia/Shanghai"] = "Kiinan normaaliaika"
    @long_daylights["Asia/Tokyo"] = "Japanin normaaliaika"
    @long_daylights["Europe/Bucharest"] = "Itä-Euroopan kesäaika"
    @long_daylights["Europe/Paris"] = "Keski-Euroopan kesäaika"
    @long_daylights["Pacific/Honolulu"] = "Havaijin normaaliaika"
    @short_generics = {}
    @short_standards = {}
    @short_standards["Africa/Casablanca"] = "GMT"
    @short_standards["America/Anchorage"] = "AST"
    @short_standards["America/Chicago"] = "CST"
    @short_standards["America/Denver"] = "MST"
    @short_standards["America/Halifax"] = "AST"
    @short_standards["America/Indianapolis"] = "EST"
    @short_standards["America/Los_Angeles"] = "PST"
    @short_standards["America/New_York"] = "EST"
    @short_standards["America/Phoenix"] = "MST"
    @short_standards["America/St_Johns"] = "CNT"
    @short_standards["Asia/Jerusalem"] = "IST"
    @short_standards["Asia/Shanghai"] = "CTT"
    @short_standards["Asia/Tokyo"] = "JST"
    @short_standards["Europe/Bucharest"] = "EET"
    @short_standards["Europe/Paris"] = "CET"
    @short_standards["Pacific/Honolulu"] = "HST"
    @short_daylights = {}
    @short_daylights["Africa/Casablanca"] = "GMT"
    @short_daylights["America/Anchorage"] = "ADT"
    @short_daylights["America/Chicago"] = "CDT"
    @short_daylights["America/Denver"] = "MDT"
    @short_daylights["America/Halifax"] = "ADT"
    @short_daylights["America/Indianapolis"] = "EST"
    @short_daylights["America/Los_Angeles"] = "PDT"
    @short_daylights["America/New_York"] = "EDT"
    @short_daylights["America/Phoenix"] = "MST"
    @short_daylights["America/St_Johns"] = "CDT"
    @short_daylights["Asia/Jerusalem"] = "IDT"
    @short_daylights["Asia/Shanghai"] = "CTT"
    @short_daylights["Asia/Tokyo"] = "JST"
    @short_daylights["Europe/Bucharest"] = "EEST"
    @short_daylights["Europe/Paris"] = "CEST"
    @short_daylights["Pacific/Honolulu"] = "HST"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
