#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/hu_HU.xml
# Original file revision: 1.27 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["America/Araguaina"] = "Araguaína"
    @exemplarcities["America/Argentina/ComodRivadavia"] = "Comodoro Rivadavia"
    @exemplarcities["America/Argentina/Rio_Gallegos"] = "Río Gallegos"
    @exemplarcities["America/Argentina/Tucuman"] = "Tucumán"
    @exemplarcities["America/Belem"] = "Belém"
    @exemplarcities["America/Cancun"] = "Cancún"
    @exemplarcities["America/Cordoba"] = "Córdoba"
    @exemplarcities["America/Cuiaba"] = "Cuiabá"
    @exemplarcities["America/Danmarkshavn"] = "Danmarks Havn"
    @exemplarcities["America/Eirunepe"] = "Eirunepé"
    @exemplarcities["America/Godthab"] = "Godthåb"
    @exemplarcities["America/Maceio"] = "Maceió"
    @exemplarcities["America/Mazatlan"] = "Mazatlán"
    @exemplarcities["America/Merida"] = "Mérida"
    @exemplarcities["America/Mexico_City"] = "Mexikóváros"
    @exemplarcities["America/Montreal"] = "Montréal"
    @exemplarcities["America/Porto_Velho"] = "Pôrto Velho"
    @exemplarcities["America/Rio_Branco"] = "Río Branco"
    @exemplarcities["America/Sao_Paulo"] = "São Paulo"
    @exemplarcities["America/Scoresbysund"] = "Scoresby Sound"
    @exemplarcities["America/St_Johns"] = "St. John's"
    @exemplarcities["Antarctica/DumontDUrville"] = "Dumont d'Urville"
    @exemplarcities["Antarctica/South_Pole"] = "Déli-sark"
    @exemplarcities["Antarctica/Vostok"] = "Vosztok"
    @exemplarcities["Asia/Almaty"] = "Alma-Ata"
    @exemplarcities["Asia/Anadyr"] = "Anadir"
    @exemplarcities["Asia/Aqtau"] = "Aktau"
    @exemplarcities["Asia/Aqtobe"] = "Aktöbe"
    @exemplarcities["Asia/Choibalsan"] = "Csojbalszan"
    @exemplarcities["Asia/Chongqing"] = "Csungking"
    @exemplarcities["Asia/Irkutsk"] = "Irkutszk"
    @exemplarcities["Asia/Jakarta"] = "Dzsakarta"
    @exemplarcities["Asia/Kamchatka"] = "Kamcsatka"
    @exemplarcities["Asia/Kashgar"] = "Kasgár"
    @exemplarcities["Asia/Krasnoyarsk"] = "Krasznojarszk"
    @exemplarcities["Asia/Magadan"] = "Magadán"
    @exemplarcities["Asia/Makassar"] = "Makasar"
    @exemplarcities["Asia/Novosibirsk"] = "Novoszibirszk"
    @exemplarcities["Asia/Omsk"] = "Omszk"
    @exemplarcities["Asia/Qyzylorda"] = "Kizilorda"
    @exemplarcities["Asia/Sakhalin"] = "Szahalin"
    @exemplarcities["Asia/Samarkand"] = "Szamarkand"
    @exemplarcities["Asia/Shanghai"] = "Sanghaj"
    @exemplarcities["Asia/Tashkent"] = "Taskent"
    @exemplarcities["Asia/Ulaanbaatar"] = "Ulan Bator"
    @exemplarcities["Asia/Urumqi"] = "Ürümqi"
    @exemplarcities["Asia/Vladivostok"] = "Vlagyivosztok"
    @exemplarcities["Asia/Yakutsk"] = "Jakutszk"
    @exemplarcities["Asia/Yekaterinburg"] = "Jekatyerinburg"
    @exemplarcities["Atlantic/Azores"] = "Azóri-szigetek"
    @exemplarcities["Atlantic/Canary"] = "Kanári-szigetek"
    @exemplarcities["Atlantic/Jan_Mayen"] = "Jan Mayen-szigetek"
    @exemplarcities["Atlantic/Madeira"] = "Madeira-sziget"
    @exemplarcities["Europe/Kaliningrad"] = "Kalinyingrád"
    @exemplarcities["Europe/Kiev"] = "Kijev"
    @exemplarcities["Europe/Lisbon"] = "Lisszabon"
    @exemplarcities["Europe/Moscow"] = "Moszkva"
    @exemplarcities["Europe/Paris"] = "Paris"
    @exemplarcities["Europe/Samara"] = "Szamara"
    @exemplarcities["Europe/Simferopol"] = "Szimferopol"
    @exemplarcities["Europe/Uzhgorod"] = "Ungvár"
    @exemplarcities["Europe/Zaporozhye"] = "Zaporozsje"
    @exemplarcities["Pacific/Chatham"] = "Chatham-szigetek"
    @exemplarcities["Pacific/Easter"] = "Húsvét-szigetek"
    @exemplarcities["Pacific/Galapagos"] = "Galapagos-szigetek"
    @exemplarcities["Pacific/Gambier"] = "Gambier-szigetek"
    @exemplarcities["Pacific/Kiritimati"] = "Kiritimati-sziget"
    @exemplarcities["Pacific/Kosrae"] = "Kosrae-szigetek"
    @exemplarcities["Pacific/Kwajalein"] = "Kwajalein-zátony"
    @exemplarcities["Pacific/Majuro"] = "Majuro-zátony"
    @exemplarcities["Pacific/Marquesas"] = "Marquesas-szigetek"
    @exemplarcities["Pacific/Midway"] = "Midway-szigetek"
    @exemplarcities["Pacific/Ponape"] = "Ponape-szigetek"
    @exemplarcities["Pacific/Tahiti"] = "Tahiti-sziget"
    @exemplarcities["Pacific/Tarawa"] = "Tarawa-sziget"
    @exemplarcities["Pacific/Truk"] = "Truk-szigetek"
    @exemplarcities["Pacific/Wake"] = "Wake-sziget"
    @exemplarcities["Pacific/Yap"] = "Yap-szigetek"
    @long_generics = {}
    @long_standards = {}
    @long_standards["Europe/Paris"] = "közép-európai idő"
    @long_daylights = {}
    @long_daylights["Europe/Paris"] = "közép-európai nyári idő"
    @short_generics = {}
    @short_standards = {}
    @short_daylights = {}
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
