#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/th_TH.xml
# Original file revision: 1.26 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HHmm;-HHmm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["America/Argentina/ComodRivadavia"] = "โคมอดริวาดาเวีย"
    @exemplarcities["America/Argentina/La_Rioja"] = "ลาริโอจา"
    @exemplarcities["America/Argentina/San_Juan"] = "ซานจวน"
    @exemplarcities["America/Argentina/Tucuman"] = "ทูคูแมน"
    @exemplarcities["America/Belem"] = "เบเลง"
    @exemplarcities["America/Boa_Vista"] = "บัววีชตา"
    @exemplarcities["America/Boise"] = "บอยซี"
    @exemplarcities["America/Cambridge_Bay"] = "อ่าวแคมบรืดจ์"
    @exemplarcities["America/Campo_Grande"] = "กัมปูกรัมดี"
    @exemplarcities["America/Catamarca"] = "คาตามาร์กา"
    @exemplarcities["America/Chicago"] = "ชิคาโก"
    @exemplarcities["America/Chihuahua"] = "ชีวาวา"
    @exemplarcities["America/Cuiaba"] = "กุยาบา"
    @exemplarcities["America/Denver"] = "เดนเวอร์"
    @exemplarcities["America/Detroit"] = "ดีทรอยต์"
    @exemplarcities["America/Edmonton"] = "เอดมันตัน"
    @exemplarcities["America/Fortaleza"] = "ฟอร์ตาเลซา"
    @exemplarcities["America/Goose_Bay"] = "กูสเบย์"
    @exemplarcities["America/Halifax"] = "แฮลิแฟกซ์"
    @exemplarcities["America/Hermosillo"] = "เอร์โมซีโย"
    @exemplarcities["America/Indianapolis"] = "อินเดียแนโพลิส"
    @exemplarcities["America/Iqaluit"] = "อีกวาลิต"
    @exemplarcities["America/Los_Angeles"] = "ลอสแองเจลิส"
    @exemplarcities["America/Maceio"] = "มาเซโอ"
    @exemplarcities["America/Manaus"] = "มาเนาส์"
    @exemplarcities["America/Mendoza"] = "เมนดูซา"
    @exemplarcities["America/Merida"] = "เมรีดา"
    @exemplarcities["America/Mexico_City"] = "เม็กซิโกซิตี"
    @exemplarcities["America/Monterrey"] = "มอนเตร์เรย์"
    @exemplarcities["America/New_York"] = "นิวยอร์ก"
    @exemplarcities["America/North_Dakota/Center"] = "เซนเตอร์"
    @exemplarcities["America/Rainy_River"] = "เรนนี่ริเวอร์"
    @exemplarcities["America/Recife"] = "เรซีเฟ"
    @exemplarcities["America/Regina"] = "ริไจนา"
    @exemplarcities["America/Rio_Branco"] = "ริโอบรังโก"
    @exemplarcities["America/Sao_Paulo"] = "เซาเปาลู"
    @exemplarcities["America/St_Johns"] = "เซนต์จอนส์"
    @exemplarcities["America/Thunder_Bay"] = "ทันเดอร์เบย์"
    @exemplarcities["America/Toronto"] = "โทรอนโต"
    @exemplarcities["America/Vancouver"] = "แวนคูเวอร์"
    @exemplarcities["America/Whitehorse"] = "ไวต์ฮอร์ส"
    @exemplarcities["America/Winnipeg"] = "วินนิเพก"
    @exemplarcities["America/Yellowknife"] = "เยลโลว์ไนฟ์"
    @exemplarcities["Antarctica/Davis"] = "เดวิส"
    @exemplarcities["Antarctica/South_Pole"] = "ขั่วโลกใต้"
    @exemplarcities["Antarctica/Vostok"] = "วอสทอก"
    @exemplarcities["Asia/Chongqing"] = "ฉงชิ่ง"
    @exemplarcities["Asia/Harbin"] = "ฮาร์บิน"
    @exemplarcities["Asia/Jakarta"] = "จาการ์ตา"
    @exemplarcities["Asia/Kuala_Lumpur"] = "กัวลาลัมเปอร์"
    @exemplarcities["Asia/Kuching"] = "กูชิง"
    @exemplarcities["Asia/Shanghai"] = "เซี่ยงไฮ้"
    @exemplarcities["Asia/Tashkent"] = "ทาชเคนต์"
    @exemplarcities["Asia/Urumqi"] = "อุรุมชี"
    @exemplarcities["Asia/Yakutsk"] = "ยาคุตสค์"
    @exemplarcities["Australia/Adelaide"] = "แอดิเลด"
    @exemplarcities["Australia/Brisbane"] = "บริสเบน"
    @exemplarcities["Australia/Broken_Hill"] = "โบรกเคนฮิว"
    @exemplarcities["Australia/Darwin"] = "ดาร์วิน"
    @exemplarcities["Australia/Hobart"] = "โฮบาร์ต"
    @exemplarcities["Australia/Lindeman"] = "ลินดีแมน"
    @exemplarcities["Australia/Lord_Howe"] = "ลอร์ดโฮวี"
    @exemplarcities["Australia/Melbourne"] = "เมลเบิร์น"
    @exemplarcities["Australia/Perth"] = "เพิิร์ท"
    @exemplarcities["Australia/Sydney"] = "ซิดนีย์ Sydney"
    @exemplarcities["Europe/Belfast"] = "เบลฟัสต์"
    @exemplarcities["Europe/London"] = "ลอนดอน"
    @exemplarcities["Europe/Madrid"] = "มาดริด"
    @exemplarcities["Europe/Moscow"] = "มอสโค"
    @exemplarcities["Pacific/Auckland"] = "โอคแลนด์"
    @exemplarcities["Pacific/Honolulu"] = "โฮโนลูลู"
    @exemplarcities["Pacific/Midway"] = "มิดเวย์"
    @long_generics = {}
    @long_standards = {}
    @long_daylights = {}
    @short_generics = {}
    @short_standards = {}
    @short_daylights = {}
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
