#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/wal_ET.xml
# Original file revision: 1.17 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["ar"] = "ዐርቢኛ"
    @languages["de"] = "ጀርመን"
    @languages["en"] = "እንግሊዝኛ"
    @languages["es"] = "ስፓኒሽ"
    @languages["fr"] = "ፈረንሳይኛ"
    @languages["hi"] = "ሐንድኛ"
    @languages["it"] = "ጣሊያንኛ"
    @languages["ja"] = "ጃፓንኛ"
    @languages["pt"] = "ፖርቱጋሊኛ"
    @languages["ru"] = "ራሽኛ"
    @languages["wal"] = "ወላይታቱ"
    @languages["zh"] = "ቻይንኛ"
    @territories = {}
    @territories["AD"] = "አንዶራ"
    @territories["AE"] = "የተባበሩት አረብ ኤምሬትስ"
    @territories["AL"] = "አልባኒያ"
    @territories["AM"] = "አርሜኒያ"
    @territories["AN"] = "ኔዘርላንድስ አንቲልስ"
    @territories["AR"] = "አርጀንቲና"
    @territories["AT"] = "ኦስትሪያ"
    @territories["AU"] = "አውስትሬሊያ"
    @territories["AZ"] = "አዘርባጃን"
    @territories["BA"] = "ቦስኒያ እና ሄርዞጎቪኒያ"
    @territories["BB"] = "ባርቤዶስ"
    @territories["BE"] = "ቤልጄም"
    @territories["BG"] = "ቡልጌሪያ"
    @territories["BH"] = "ባህሬን"
    @territories["BM"] = "ቤርሙዳ"
    @territories["BO"] = "ቦሊቪያ"
    @territories["BR"] = "ብራዚል"
    @territories["BT"] = "ቡህታን"
    @territories["BY"] = "ቤላሩስ"
    @territories["BZ"] = "ቤሊዘ"
    @territories["CD"] = "ኮንጎ"
    @territories["CF"] = "የመካከለኛው አፍሪካ ሪፐብሊክ"
    @territories["CH"] = "ስዊዘርላንድ"
    @territories["CL"] = "ቺሊ"
    @territories["CM"] = "ካሜሩን"
    @territories["CN"] = "ቻይና"
    @territories["CO"] = "ኮሎምቢያ"
    @territories["CS"] = "ሰርቢያ"
    @territories["CV"] = "ኬፕ ቬርዴ"
    @territories["CY"] = "ሳይፕረስ"
    @territories["CZ"] = "ቼክ ሪፑብሊክ"
    @territories["DE"] = "ጀርመን"
    @territories["DK"] = "ዴንማርክ"
    @territories["DM"] = "ዶሚኒካ"
    @territories["DO"] = "ዶሚኒክ ሪፑብሊክ"
    @territories["DZ"] = "አልጄሪያ"
    @territories["EC"] = "ኢኳዶር"
    @territories["EE"] = "ኤስቶኒያ"
    @territories["EG"] = "ግብጽ"
    @territories["EH"] = "ምዕራባዊ ሳህራ"
    @territories["ER"] = "ኤርትራ"
    @territories["ES"] = "ስፔን"
    @territories["ET"] = "ኢትዮጵያ"
    @territories["FI"] = "ፊንላንድ"
    @territories["FJ"] = "ፊጂ"
    @territories["FM"] = "ሚክሮኔዢያ"
    @territories["FR"] = "ፈረንሳይ"
    @territories["GB"] = "እንግሊዝ"
    @territories["GE"] = "ጆርጂያ"
    @territories["GF"] = "የፈረንሳይ ጉዊአና"
    @territories["GM"] = "ጋምቢያ"
    @territories["GN"] = "ጊኒ"
    @territories["GQ"] = "ኢኳቶሪያል ጊኒ"
    @territories["GR"] = "ግሪክ"
    @territories["GW"] = "ቢሳዎ"
    @territories["GY"] = "ጉያና"
    @territories["HK"] = "ሆንግ ኮንግ"
    @territories["HR"] = "ክሮኤሽያ"
    @territories["HT"] = "ሀይቲ"
    @territories["HU"] = "ሀንጋሪ"
    @territories["ID"] = "ኢንዶኔዢያ"
    @territories["IE"] = "አየርላንድ"
    @territories["IL"] = "እስራኤል"
    @territories["IN"] = "ህንድ"
    @territories["IQ"] = "ኢራቅ"
    @territories["IS"] = "አይስላንድ"
    @territories["IT"] = "ጣሊያን"
    @territories["JM"] = "ጃማይካ"
    @territories["JO"] = "ጆርዳን"
    @territories["JP"] = "ጃፓን"
    @territories["KH"] = "ካምቦዲያ"
    @territories["KM"] = "ኮሞሮስ"
    @territories["KP"] = "ደቡብ ኮሪያ"
    @territories["KR"] = "ሰሜን ኮሪያ"
    @territories["KW"] = "ክዌት"
    @territories["LB"] = "ሊባኖስ"
    @territories["LT"] = "ሊቱዌኒያ"
    @territories["LV"] = "ላትቪያ"
    @territories["LY"] = "ሊቢያ"
    @territories["MA"] = "ሞሮኮ"
    @territories["MD"] = "ሞልዶቫ"
    @territories["MK"] = "ማከዶኒያ"
    @territories["MN"] = "ሞንጎሊያ"
    @territories["MO"] = "ማካዎ"
    @territories["MR"] = "ሞሪቴኒያ"
    @territories["MT"] = "ማልታ"
    @territories["MU"] = "ማሩሸስ"
    @territories["MX"] = "ሜክሲኮ"
    @territories["MY"] = "ማሌዢያ"
    @territories["NA"] = "ናሚቢያ"
    @territories["NC"] = "ኒው ካሌዶኒያ"
    @territories["NG"] = "ናይጄሪያ"
    @territories["NL"] = "ኔዘርላንድ"
    @territories["NO"] = "ኖርዌ"
    @territories["NP"] = "ኔፓል"
    @territories["NZ"] = "ኒው ዚላንድ"
    @territories["PE"] = "ፔሩ"
    @territories["PF"] = "የፈረንሳይ ፖሊኔዢያ"
    @territories["PG"] = "ፓፑዋ ኒው ጊኒ"
    @territories["PL"] = "ፖላንድ"
    @territories["PR"] = "ፖርታ ሪኮ"
    @territories["RO"] = "ሮሜኒያ"
    @territories["RU"] = "ራሺያ"
    @territories["SA"] = "ሳውድአረቢያ"
    @territories["SD"] = "ሱዳን"
    @territories["SE"] = "ስዊድን"
    @territories["SG"] = "ሲንጋፖር"
    @territories["SI"] = "ስሎቬኒያ"
    @territories["SK"] = "ስሎቫኪያ"
    @territories["SN"] = "ሴኔጋል"
    @territories["SO"] = "ሱማሌ"
    @territories["SY"] = "ሲሪያ"
    @territories["TD"] = "ቻድ"
    @territories["TF"] = "የፈረንሳይ ደቡባዊ ግዛቶች"
    @territories["TH"] = "ታይላንድ"
    @territories["TJ"] = "ታጃኪስታን"
    @territories["TL"] = "ምስራቅ ቲሞር"
    @territories["TN"] = "ቱኒዚያ"
    @territories["TR"] = "ቱርክ"
    @territories["TT"] = "ትሪኒዳድ እና ቶባጎ"
    @territories["TZ"] = "ታንዛኒያ"
    @territories["UG"] = "ዩጋንዳ"
    @territories["US"] = "አሜሪካ"
    @territories["UZ"] = "ዩዝበኪስታን"
    @territories["VE"] = "ቬንዙዌላ"
    @territories["VG"] = "የእንግሊዝ ድንግል ደሴቶች"
    @territories["VI"] = "የአሜሪካ ቨርጂን ደሴቶች"
    @territories["YE"] = "የመን"
    @territories["ZA"] = "ደቡብ አፍሪካ"
    @territories["ZM"] = "ዛምቢያ"
    @scripts = {}
    @scripts["Latn"] = "ላቲን"
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[ሀ-ቈቊ-ቍቐ-ቖቘቚ-ቝበ-ኈኊ-ኍነ-ኰኲ-ኵኸ-ኾዀዂ-ዅወ-ዖዘ-ጐጒ-ጕጘ-ፚ፟-፼ᎀ-᎙ⶀ-ⶖⶠ-ⶦⶨ-ⶮⶰ-ⶶⶸ-ⶾⷀ-ⷆⷈ-ⷎⷐ-ⷖⷘ-ⷞ]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
