#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/te_IN.xml
# Original file revision: 1.34 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["ar"] = "అరబిక్"
    @languages["de"] = "ఙర్మన్"
    @languages["en"] = "ఆంగ్లం"
    @languages["es"] = "స్పానిష్"
    @languages["fr"] = "ఫ్రెంచ్"
    @languages["hi"] = "హిందీ"
    @languages["it"] = "ఇటాలియన్ భాష"
    @languages["ja"] = "జపాను భాష"
    @languages["pt"] = "పొర్చుగల్ భాష"
    @languages["ru"] = "రష్యన్ భాష"
    @languages["te"] = "తెలుగు"
    @languages["zh"] = "చైనా భాష"
    @territories = {}
    @territories["BR"] = "బ్రజిల్"
    @territories["CN"] = "చైనా"
    @territories["DE"] = "ఙర్మని"
    @territories["FR"] = "ఫ్రాన్స్‌"
    @territories["GB"] = "బ్రిటన్"
    @territories["IN"] = "భారత దేళం"
    @territories["IT"] = "ఇటలి"
    @territories["JP"] = "జపాసు"
    @territories["RU"] = "రష్య"
    @territories["US"] = "ఐక్య రాష్ట్ర అమెరిక"
    @scripts = {}
    @scripts["Latn"] = "లాటిన్"
    @scripts["Telu"] = "తెలుగు"
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[ఁ-ఃఅ-ఌఎ-ఐఒ-నప-ళవ-హా-ౄె-ైొ-్ౕౖౠౡ౦-౯‌‍]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "'"
    @delimiter_quotation_end = "'"
    @delimiter_alternate_quotation_start = """
    @delimiter_alternate_quotation_end = """
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "అవను"
    @nostr = "కాదు"
    @yesexpr = "^([yY]([eE][sS])?)|అవను"
    @noexpr = "^([nN][oO]?)|కాదు"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
