#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/ps_AF.xml
# Original file revision: 1.27 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["ar"] = "عربي"
    @languages["bal"] = "بلوڅي"
    @languages["de"] = "الماني"
    @languages["el"] = "یوناني"
    @languages["en"] = "انګلیسي"
    @languages["et"] = "حبشي"
    @languages["fa"] = "فارسي"
    @languages["fi"] = "فینلنډي"
    @languages["fr"] = "فرانسوي"
    @languages["he"] = "عبري"
    @languages["hi"] = "هندي"
    @languages["hy"] = "ارمني"
    @languages["ine"] = "هند و اروپایي"
    @languages["it"] = "ایټالوي"
    @languages["ja"] = "جاپانی"
    @languages["ku"] = "کردي"
    @languages["la"] = "لاتیني"
    @languages["mg"] = "ملغاسي"
    @languages["mk"] = "مقدوني"
    @languages["mn"] = "مغولي"
    @languages["ms"] = "ملایا"
    @languages["pl"] = "پولنډي"
    @languages["ps"] = "پښتو"
    @languages["pt"] = "پورتګالي"
    @languages["ru"] = "روسي"
    @languages["sa"] = "سنسکریټ"
    @languages["sv"] = "سویډنی"
    @languages["tg"] = "تاجک"
    @languages["tk"] = "ترکمني"
    @languages["tt"] = "تاتار"
    @languages["uz"] = "ازبکي"
    @languages["zh"] = "چیني"
    @territories = {}
    @territories["AF"] = "افغانستان"
    @territories["AL"] = "البانیه"
    @territories["AO"] = "انګولا"
    @territories["AQ"] = "انتارکتیکا"
    @territories["AT"] = "اتریش"
    @territories["BD"] = "بنګله‌دیش"
    @territories["BG"] = "بلغاریه"
    @territories["CA"] = "کاناډا"
    @territories["CH"] = "سویس"
    @territories["CN"] = "چین"
    @territories["CO"] = "کولمبیا"
    @territories["CU"] = "کیوبا"
    @territories["DE"] = "المان"
    @territories["DK"] = "ډنمارک"
    @territories["DZ"] = "الجزایر"
    @territories["EG"] = "مصر"
    @territories["ES"] = "هسپانیه"
    @territories["ET"] = "حبشه"
    @territories["FI"] = "فنلینډ"
    @territories["FR"] = "فرانسه"
    @territories["GB"] = "برتانیه"
    @territories["GH"] = "ګانا"
    @territories["GN"] = "ګیانا"
    @territories["GR"] = "یونان"
    @territories["GT"] = "ګواتیمالا"
    @territories["HK"] = "هانکانګ"
    @territories["HN"] = "هانډوراس"
    @territories["HU"] = "مجارستان"
    @territories["ID"] = "اندونیزیا"
    @territories["IN"] = "هند"
    @territories["IQ"] = "عراق"
    @territories["IS"] = "آیسلینډ"
    @territories["IT"] = "ایټالیه"
    @territories["JM"] = "جمیکا"
    @territories["JP"] = "جاپان"
    @territories["KH"] = "کمبودیا"
    @territories["KW"] = "کویټ"
    @territories["LA"] = "لاوس"
    @territories["LB"] = "لبنان"
    @territories["LR"] = "لایبریا"
    @territories["LY"] = "لیبیا"
    @territories["MA"] = "مراکش"
    @territories["MN"] = "مغولستان"
    @territories["MY"] = "مالیزیا"
    @territories["NG"] = "نایجیریا"
    @territories["NI"] = "نکاراګوا"
    @territories["NL"] = "هالېنډ"
    @territories["NO"] = "ناروې"
    @territories["NP"] = "نیپال"
    @territories["NZ"] = "نیوزیلنډ"
    @territories["PK"] = "پاکستان"
    @territories["PL"] = "پولنډ"
    @territories["PS"] = "فلسطین"
    @territories["PT"] = "پورتګال"
    @territories["RU"] = "روسیه"
    @territories["RW"] = "روندا"
    @territories["SA"] = "سعودی عربستان"
    @territories["SE"] = "سویډن"
    @territories["SV"] = "سالوېډور"
    @territories["SY"] = "سوریه"
    @territories["TJ"] = "تاجکستان"
    @territories["TZ"] = "تنزانیا"
    @territories["UY"] = "یوروګوای"
    @territories["YE"] = "یمن"
    @scripts = {}
    @layout_orientation = "right-to-left"
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[ء-ؤئ-غفقل-وي-ْٰٔټپځڅ-چډړږژښکګڼی-ۍې ‌‍‏‎]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
