#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/af_ZA.xml
# Original file revision: 1.27 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["af"] = "Afrikaans"
    @territories = {}
    @territories["AE"] = "Verenigde Arabiese Emirate"
    @territories["AF"] = "Afganistan"
    @territories["AG"] = "Antigua en Barbuda"
    @territories["AL"] = "Albanië"
    @territories["AM"] = "Armenië"
    @territories["AR"] = "Argentinië"
    @territories["AT"] = "Oostenryk"
    @territories["AU"] = "Australië"
    @territories["AZ"] = "Aserbeidjan"
    @territories["BA"] = "Bosnië en Herzegowina"
    @territories["BD"] = "Bangladesj"
    @territories["BE"] = "België"
    @territories["BF"] = "Boerkina Fasso"
    @territories["BG"] = "Bulgarye"
    @territories["BH"] = "Bahrein"
    @territories["BN"] = "Broenei"
    @territories["BO"] = "Bolivië"
    @territories["BR"] = "Brasilië"
    @territories["BT"] = "Bhoetan"
    @territories["BY"] = "Wit-Rusland"
    @territories["CA"] = "Kanada"
    @territories["CF"] = "Sentraal-Afrikaanse Republiek"
    @territories["CG"] = "Kongo"
    @territories["CH"] = "Switserland"
    @territories["CI"] = "Ivoorkus"
    @territories["CL"] = "Chili"
    @territories["CM"] = "Kameroen"
    @territories["CN"] = "Sjina"
    @territories["CS"] = "Serwië"
    @territories["CU"] = "Kuba"
    @territories["CV"] = "Kaap Verde"
    @territories["CY"] = "Ciprus"
    @territories["CZ"] = "Tjeggiese Republiek"
    @territories["DE"] = "Duitsland"
    @territories["DJ"] = "Djiboeti"
    @territories["DK"] = "Denemarke"
    @territories["DO"] = "Dominikaanse Republiek"
    @territories["DZ"] = "Algerië"
    @territories["EE"] = "Estland"
    @territories["EG"] = "Egipte"
    @territories["EH"] = "Wes-Sahara"
    @territories["ES"] = "Spanje"
    @territories["ET"] = "Ethiopië"
    @territories["FJ"] = "Fidji"
    @territories["FM"] = "Mikronesië"
    @territories["FR"] = "Frankryk"
    @territories["GA"] = "Gaboen"
    @territories["GB"] = "Groot-Brittanje"
    @territories["GE"] = "Georgië"
    @territories["GM"] = "Gambië"
    @territories["GN"] = "Guinee"
    @territories["GQ"] = "Ekwatoriaal-Guinee"
    @territories["GR"] = "Griekeland"
    @territories["GW"] = "Guinee-Bissau"
    @territories["HR"] = "Kroasië"
    @territories["HT"] = "Haïti"
    @territories["HU"] = "Hongarye"
    @territories["ID"] = "Indonesië"
    @territories["IE"] = "Ierland"
    @territories["IN"] = "Indië"
    @territories["IQ"] = "Irak"
    @territories["IS"] = "Ysland"
    @territories["IT"] = "Italië"
    @territories["JM"] = "Jamaika"
    @territories["JO"] = "Jordanië"
    @territories["KE"] = "Kenia"
    @territories["KG"] = "Kirgisië"
    @territories["KH"] = "Kambodja"
    @territories["KM"] = "Comore"
    @territories["KN"] = "Saint Kitts en Nevis"
    @territories["KP"] = "Noord-Korea"
    @territories["KR"] = "Suid-Korea"
    @territories["KW"] = "Koeweit"
    @territories["KZ"] = "Kasakstan"
    @territories["LB"] = "Libanon"
    @territories["LR"] = "Liberië"
    @territories["LT"] = "Litaue"
    @territories["LU"] = "Luxemburg"
    @territories["LV"] = "Letland"
    @territories["LY"] = "Libië"
    @territories["MA"] = "Marokko"
    @territories["MG"] = "Madagaskar"
    @territories["MH"] = "Marshall-eilande"
    @territories["MK"] = "Macedonië"
    @territories["MN"] = "Mongolië"
    @territories["MR"] = "Mouritanië"
    @territories["MV"] = "Maldive"
    @territories["MX"] = "Meksiko"
    @territories["MY"] = "Maleisië"
    @territories["MZ"] = "Mosambiek"
    @territories["NA"] = "Namibië"
    @territories["NE"] = "Nigerië"
    @territories["NL"] = "Nederland"
    @territories["NO"] = "Noorweë"
    @territories["NR"] = "Naoeroe"
    @territories["NZ"] = "Nieu-Seeland"
    @territories["PG"] = "Papoea Nieu-Guinee"
    @territories["PH"] = "Filippyne"
    @territories["PL"] = "Pole"
    @territories["QA"] = "Katar"
    @territories["RO"] = "Roemenië"
    @territories["RU"] = "Rusland"
    @territories["SA"] = "Saoedi-Arabië"
    @territories["SB"] = "Solomon Eilande"
    @territories["SC"] = "Seychelle"
    @territories["SD"] = "Soedan"
    @territories["SE"] = "Swede"
    @territories["SG"] = "Singapoer"
    @territories["SI"] = "Slowenië"
    @territories["SK"] = "Slowakye"
    @territories["SO"] = "Somalië"
    @territories["ST"] = "Sao Tome en Principe"
    @territories["SV"] = "Salvador"
    @territories["SY"] = "Sirië"
    @territories["TD"] = "Tsjaad"
    @territories["TJ"] = "Tadjikistan"
    @territories["TM"] = "Turkmenië"
    @territories["TN"] = "Tunisië"
    @territories["TR"] = "Turkye"
    @territories["TT"] = "Trinidad en Tobago"
    @territories["TZ"] = "Tanzanië"
    @territories["UA"] = "Oekraine"
    @territories["US"] = "Verenigde State van Amerika"
    @territories["UZ"] = "Oesbekistan"
    @territories["VA"] = "Vatikaan"
    @territories["VC"] = "Saint Vincent en die Grenadine"
    @territories["VN"] = "Viëtnam"
    @territories["YE"] = "Jemen"
    @territories["ZA"] = "Suid-Afrika"
    @territories["ZM"] = "Zambië"
    @scripts = {}
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[a-záéèâêîôûëïöŉ]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "‘"
    @delimiter_quotation_end = "’"
    @delimiter_alternate_quotation_start = "“"
    @delimiter_alternate_quotation_end = "”"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
