#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/th.xml
# Original file revision: 1.49 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @format = "¤ #,##0.00"
    @before_match = "[:letter:]"
    @before_match_surrounding = "[:digit:]"
    @before_insertbetween = " "
    @after_match = "[:letter:]"
    @after_match_surrounding = "[:digit:]"
    @after_insertbetween = " "
    @currencies = {}
    @currencies["ARP"] = "เปโซอาร์เจนติน่า (1983-1985)"
    @currencies["ARS"] = "เปโซอาร์เจนติน่า"
    @currencies["ATS"] = "ชิลลิงออสเตรีย"
    @currencies["AUD"] = "เหรียญออสเตรเลีย"
    @currencies["BRL"] = "รีล"
    @currencies["CAD"] = "เหรียญคานาดา"
    @currencies["CLP"] = "เปโซชิลี"
    @currencies["CNY"] = "หยวนเหรินเหมินบี้"
    @currencies["EUR"] = "ยูโร"
    @currencies["FJD"] = "เหรียญฟิจิ"
    @currencies["FRF"] = "เหรียญฝรั่งเศส"
    @currencies["GBP"] = "ปอนด์สเตอร์ลิงอังกฤษ"
    @currencies["HKD"] = "เหรียญฮ่องกง"
    @currencies["IDR"] = "รูเปียอินโดนีเซีย"
    @currencies["IEP"] = "ปอนด์ไอริช"
    @currencies["ILP"] = "ปอนด์อิสราเอล"
    @currencies["INR"] = "รูปีอินเดีย"
    @currencies["ITL"] = "ITL"
    @currencies["JPY"] = "เยน"
    @currencies["MXN"] = "เปโซแม็กซิโก"
    @currencies["MYR"] = "ริงกิตมาเลเซีย"
    @currencies["NZD"] = "เหรียญนิวซีแลนด์"
    @currencies["PHP"] = "เปโซฟิลิปปินส์"
    @currencies["PKR"] = "รูปีปากีสถาน"
    @currencies["RUB"] = "รูเบิลรัสเซีย"
    @currencies["SGD"] = "เหรียญสิงคโปร์"
    @currencies["THB"] = "บาท"
    @currencies["TRY"] = "ตุรกี ลีร่า ใหม่"
    @currencies["USD"] = "ดอร์ล่าร์สหรัฐ"
    @currencies["USN"] = "เหรียญสหรัฐ (วันถัดไป)"
    @currencies["USS"] = "เหรียญสหรัฐ (วันเดียวกัน)"
    @currencies["XAU"] = "ทอง"
    @symbols = {}
    @symbols["ARS"] = "Arg$"
    @symbols["AUD"] = "$A"
    @symbols["CAD"] = "Can$"
    @symbols["CLP"] = "Ch$"
    @symbols["CNY"] = "￥"
    @symbols["EUR"] = "€"
    @symbols["FJD"] = "F$"
    @symbols["GBP"] = "\u00A3"
    @symbols["HKD"] = "HK$"
    @symbols["IDR"] = "Rp"
    @symbols["IEP"] = "IR\u00A3"
    @symbols["INR"] = "=0#Rs.|1#Re.|1<Rs."
    @symbols["ITL"] = "₤"
    @symbols["JPY"] = "\u00A5"
    @symbols["MXN"] = "MEX$"
    @symbols["MYR"] = "RM"
    @symbols["NZD"] = "$NZ"
    @symbols["PKR"] = "Pra"
    @symbols["SGD"] = "S$"
    @symbols["THB"] = "฿"
    @symbols["USD"] = "US$"
  end

  public
  attr_reader :format
  attr_reader :before_match
  attr_reader :before_match_surrounding
  attr_reader :before_insertbetween
  attr_reader :after_match
  attr_reader :after_match_surrounding
  attr_reader :after_insertbetween
  attr_reader :currencies
  attr_reader :symbols
