#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/bn_IN.xml
# Original file revision: 1.33 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["bn"] = "বাংলা"
    @territories = {}
    @territories["AF"] = "আফগানিস্তান"
    @territories["AL"] = "আলব্যানিয়া"
    @territories["AM"] = "আর্মেনিয়া"
    @territories["AR"] = "আর্জেণ্টাইনা"
    @territories["AT"] = "অস্ট্রিয়া"
    @territories["AU"] = "অস্ট্রেলিয়া"
    @territories["AZ"] = "আজারবাইজান"
    @territories["BD"] = "বাংলাদেশ"
    @territories["BE"] = "বেল্জিয়ম"
    @territories["BG"] = "বুলগেরিয়া"
    @territories["BO"] = "বোলিভিয়া"
    @territories["BR"] = "ব্রাজিল"
    @territories["BT"] = "ভুটান"
    @territories["BY"] = "বেলোরুশিয়া"
    @territories["CG"] = "কঙ্গো"
    @territories["CH"] = "সুইজর্লণ্ড"
    @territories["CL"] = "চিলি"
    @territories["CN"] = "চীন"
    @territories["CO"] = "কোলোম্বিয়া"
    @territories["CR"] = "কোস্টারিকা"
    @territories["CU"] = "কিউবা"
    @territories["CZ"] = "চেকিয়া"
    @territories["DE"] = "জার্মানি"
    @territories["DK"] = "ডেন্মার্ক"
    @territories["DZ"] = "এলজিরিয়া"
    @territories["EC"] = "ইকোয়াডর"
    @territories["EE"] = "এস্তোনিয়া"
    @territories["EG"] = "মিশর"
    @territories["EH"] = "পশ্চিমী সাহারা"
    @territories["ES"] = "স্পেন"
    @territories["ET"] = "ইফিওপিয়া"
    @territories["FI"] = "ফিন্ল্যাণ্ড"
    @territories["FR"] = "ফ্রান্স"
    @territories["GB"] = "গ্রেটবৃটেন"
    @territories["GE"] = "জর্জিয়া"
    @territories["GH"] = "গানা"
    @territories["GR"] = "গ্রীস্"
    @territories["GT"] = "গোয়াটিমালা"
    @territories["GY"] = "গিয়ানা"
    @territories["HN"] = "হণ্ডুরাস"
    @territories["HU"] = "হাঙ্গেরি"
    @territories["ID"] = "ইন্দোনেশিয়া"
    @territories["IE"] = "আয়ার্লণ্ড"
    @territories["IL"] = "ইস্রায়েল"
    @territories["IN"] = "ভারত"
    @territories["IQ"] = "ইরাক"
    @territories["IR"] = "ইরান"
    @territories["IS"] = "আইসলণ্ড"
    @territories["IT"] = "ইতালী"
    @territories["JM"] = "জ্যামেকা"
    @territories["JO"] = "জর্ডন"
    @territories["JP"] = "জাপান"
    @territories["KE"] = "কেনিয়া"
    @territories["KG"] = "কির্গিজিয়া"
    @territories["KH"] = "কাম্বোজ"
    @territories["KR"] = "দক্ষিণ কোরিয়া"
    @territories["KZ"] = "কাজাকস্থান"
    @territories["LA"] = "লাওস"
    @territories["LB"] = "লেবানন"
    @territories["LK"] = "শ্রীলঙ্কা"
    @territories["LR"] = "লাইবিরিয়া"
    @territories["LT"] = "লিত্ভা"
    @territories["LU"] = "লাক্সেমবার্গ"
    @territories["LV"] = "লাত্ভিয়া"
    @territories["LY"] = "লিবিয়া"
    @territories["MA"] = "মোরক্কো"
    @territories["MD"] = "মোল্দাভিয়া"
    @territories["MG"] = "মাদাগাস্কার"
    @territories["MN"] = "মঙ্গোলিয়া"
    @territories["MX"] = "মক্সিকো"
    @territories["MY"] = "মাল্যাশিয়া"
    @territories["NI"] = "নিকারাগোয়া"
    @territories["NL"] = "হলণ্ড"
    @territories["NO"] = "নরওয়ে"
    @territories["NP"] = "নেপাল"
    @territories["NZ"] = "নিউ জিলণ্ড"
    @territories["PA"] = "পানামা"
    @territories["PE"] = "পিরু"
    @territories["PH"] = "ফিলিপাইন"
    @territories["PK"] = "পাকিস্তান"
    @territories["PL"] = "পোল্যাণ্ড"
    @territories["PT"] = "পর্তুগাল"
    @territories["PY"] = "প্যারাগোয়ে"
    @territories["RO"] = "রুমানিয়া"
    @territories["RU"] = "রাশিয়া"
    @territories["SA"] = "সাউদি আরব"
    @territories["SD"] = "সুদান"
    @territories["SE"] = "সুইডেন"
    @territories["SG"] = "সিঙ্গাপুর"
    @territories["SK"] = "শ্লোভাকিয়া"
    @territories["SO"] = "সোমালি"
    @territories["SV"] = "সালভেডর"
    @territories["SY"] = "সিরিয়া"
    @territories["TH"] = "থাই"
    @territories["TJ"] = "তাজিকস্থান"
    @territories["TM"] = "তুর্কমেনিয়া"
    @territories["TN"] = "টিউনিস্"
    @territories["TR"] = "তুরস্ক"
    @territories["TW"] = "তাইওয়ান"
    @territories["UA"] = "ইউক্রেইন"
    @territories["US"] = "মার্কিন যুক্তরাষ্ট্র"
    @territories["UY"] = "উরুগোয়ে"
    @territories["UZ"] = "উজ্বেকিস্থান"
    @territories["VE"] = "ভেনেজুয়েলা"
    @territories["VN"] = "ভিয়েতনাম"
    @territories["YE"] = "ইমেন"
    @territories["ZA"] = "দক্ষিণ আফ্রিকা"
    @scripts = {}
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[ঁ-ঃঅ-ঌএঐও-নপ-রলশ-হ়-ৄেৈো-ৎৗড়ঢ়য়-ৣ০-৺‌‍]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "হ্য়াঁ"
    @nostr = "না"
    @yesexpr = "^([yY]([eE][sS])?)|হ্য়াঁ"
    @noexpr = "^([nN][oO]?)|না"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
