#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/fr_MC.xml
# Original file revision: 1.20 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Timbuktu"] = "Tombouctou"
    @exemplarcities["America/Argentina/ComodRivadavia"] = "Comodoro Rivadavia"
    @exemplarcities["America/Detroit"] = "Détroit"
    @exemplarcities["America/Manaus"] = "Manaos"
    @exemplarcities["America/Mexico_City"] = "Mexico"
    @exemplarcities["America/Montreal"] = "Montréal"
    @exemplarcities["America/St_Johns"] = "Saint-Jean de Terre-Neuve"
    @exemplarcities["Antarctica/DumontDUrville"] = "Dumont d'Urville"
    @exemplarcities["Antarctica/McMurdo"] = "Mac Murdo"
    @exemplarcities["Antarctica/South_Pole"] = "Pôle Sud"
    @exemplarcities["Asia/Almaty"] = "Alma Ata"
    @exemplarcities["Asia/Aqtau"] = "Chevtchenko"
    @exemplarcities["Asia/Aqtobe"] = "Aktioubinsk"
    @exemplarcities["Asia/Choibalsan"] = "Tchoïbalsan"
    @exemplarcities["Asia/Irkutsk"] = "Irkoutsk"
    @exemplarcities["Asia/Jerusalem"] = "Jérusalem"
    @exemplarcities["Asia/Kamchatka"] = "Kamtchatka"
    @exemplarcities["Asia/Kashgar"] = "Kachgar"
    @exemplarcities["Asia/Krasnoyarsk"] = "Krasnoïarsk"
    @exemplarcities["Asia/Novosibirsk"] = "Novossibirsk"
    @exemplarcities["Asia/Oral"] = "Ouralsk"
    @exemplarcities["Asia/Qyzylorda"] = "Kzyl Orda"
    @exemplarcities["Asia/Sakhalin"] = "Sakhaline"
    @exemplarcities["Asia/Tokyo"] = "Tokyo"
    @exemplarcities["Asia/Ulaanbaatar"] = "Oulan-Bator"
    @exemplarcities["Asia/Yakutsk"] = "Iakoutsk"
    @exemplarcities["Asia/Yekaterinburg"] = "Ekaterinbourg"
    @exemplarcities["Atlantic/Azores"] = "Açores"
    @exemplarcities["Atlantic/Canary"] = "Îles Canaries"
    @exemplarcities["Atlantic/Madeira"] = "Madère"
    @exemplarcities["Australia/Adelaide"] = "Adélaïde"
    @exemplarcities["Europe/Bucharest"] = "Bucarest"
    @exemplarcities["Europe/Lisbon"] = "Lisbonne"
    @exemplarcities["Europe/London"] = "Londres"
    @exemplarcities["Europe/Moscow"] = "Moscou"
    @exemplarcities["Europe/Paris"] = "Paris"
    @exemplarcities["Europe/Uzhgorod"] = "Oujgorod"
    @exemplarcities["Europe/Zaporozhye"] = "Zaporojie"
    @exemplarcities["Pacific/Easter"] = "Île de Pâques"
    @exemplarcities["Pacific/Marquesas"] = "Marquises"
    @long_generics = {}
    @long_generics["America/Anchorage"] = "Heure de l’Alaska"
    @long_generics["America/Chicago"] = "Heure du Centre (ÉUA)"
    @long_generics["America/Denver"] = "Heure des Rocheuses (ÉUA)"
    @long_generics["America/Edmonton"] = "Heure des Rocheuses"
    @long_generics["America/Halifax"] = "Heure de l’Atlantique"
    @long_generics["America/Indianapolis"] = "Heure de l’Est (ÉUA)"
    @long_generics["America/Los_Angeles"] = "Heure du Pacifique (ÉUA)"
    @long_generics["America/Montreal"] = "Heure de l’Est"
    @long_generics["America/New_York"] = "Heure de l’Est (ÉUA)"
    @long_generics["America/Phoenix"] = "Heure des Rocheuses (ÉUA)"
    @long_generics["America/St_Johns"] = "Heure de Terre-Neuve"
    @long_generics["America/Vancouver"] = "Heure du Pacifique"
    @long_generics["America/Winnipeg"] = "Heure du Centre"
    @long_generics["Europe/Paris"] = "Heure de l’Europe centrale"
    @long_generics["Pacific/Honolulu"] = "Heure d’Hawaï"
    @long_standards = {}
    @long_standards["America/Anchorage"] = "Heure normale de l’Alaska"
    @long_standards["America/Chicago"] = "Heure normale du Centre (ÉUA)"
    @long_standards["America/Denver"] = "Heure normale des Rocheuses (ÉUA)"
    @long_standards["America/Edmonton"] = "Heure normale des Rocheuses"
    @long_standards["America/Halifax"] = "Heure normale de l’Atlantique"
    @long_standards["America/Indianapolis"] = "Heure normale de l’Est (ÉUA)"
    @long_standards["America/Los_Angeles"] = "Heure normale du Pacifique (ÉUA)"
    @long_standards["America/Montreal"] = "Heure normale de l’Est"
    @long_standards["America/New_York"] = "Heure normale de l’Est (ÉUA)"
    @long_standards["America/Phoenix"] = "Heure normale des Rocheuses (ÉUA)"
    @long_standards["America/St_Johns"] = "Heure normale de Terre-Neuve"
    @long_standards["America/Vancouver"] = "Heure normale du Pacifique"
    @long_standards["America/Winnipeg"] = "Heure normale du Centre"
    @long_standards["Asia/Jerusalem"] = "Heure normale d’Israël"
    @long_standards["Asia/Shanghai"] = "Heure normale de Chine"
    @long_standards["Asia/Tokyo"] = "Heure normale du Japon"
    @long_standards["Europe/Bucharest"] = "Heure normale de l’Europe de l’Est"
    @long_standards["Europe/Paris"] = "Heure normale de l’Europe centrale"
    @long_standards["Pacific/Honolulu"] = "Heure normale d’Hawaï"
    @long_daylights = {}
    @long_daylights["America/Anchorage"] = "Heure avancée de l’Alaska"
    @long_daylights["America/Chicago"] = "Heure avancée du Centre (ÉUA)"
    @long_daylights["America/Denver"] = "Heure avancée des Rocheuses (ÉUA)"
    @long_daylights["America/Edmonton"] = "Heure avancée des Rocheuses"
    @long_daylights["America/Halifax"] = "Heure avancée de l’Atlantique"
    @long_daylights["America/Indianapolis"] = "Heure avancée de l’Est (ÉUA)"
    @long_daylights["America/Los_Angeles"] = "Heure avancée du Pacifique (ÉUA)"
    @long_daylights["America/Montreal"] = "Heure avancée de l’Est"
    @long_daylights["America/New_York"] = "Heure avancée de l’Est (ÉUA)"
    @long_daylights["America/Phoenix"] = "Heure avancée des Rocheuses (ÉUA)"
    @long_daylights["America/St_Johns"] = "Heure avancée de Terre-Neuve"
    @long_daylights["America/Vancouver"] = "Heure avancée du Pacifique"
    @long_daylights["America/Winnipeg"] = "Heure avancée du Centre"
    @long_daylights["Asia/Jerusalem"] = "Heure avancée d’Israël"
    @long_daylights["Asia/Shanghai"] = "Heure avancée de Chine"
    @long_daylights["Asia/Tokyo"] = "Heure avancée du Japon"
    @long_daylights["Europe/Bucharest"] = "Heure avancée de l’Europe de l’Est"
    @long_daylights["Europe/Paris"] = "Heure avancée de l’Europe centrale"
    @long_daylights["Pacific/Honolulu"] = "Heure avancée d’Hawaï"
    @short_generics = {}
    @short_generics["America/Anchorage"] = "HAK"
    @short_generics["America/Chicago"] = "HC (ÉUA)"
    @short_generics["America/Denver"] = "HR (ÉUA)"
    @short_generics["America/Edmonton"] = "HR"
    @short_generics["America/Halifax"] = "HA"
    @short_generics["America/Indianapolis"] = "HE (ÉUA)"
    @short_generics["America/Los_Angeles"] = "HP (ÉUA)"
    @short_generics["America/Montreal"] = "HE"
    @short_generics["America/New_York"] = "HE (ÉUA)"
    @short_generics["America/Phoenix"] = "HR (ÉUA)"
    @short_generics["America/St_Johns"] = "HT"
    @short_generics["America/Vancouver"] = "HP"
    @short_generics["America/Winnipeg"] = "HC"
    @short_generics["Europe/Paris"] = "HEC"
    @short_generics["Pacific/Honolulu"] = "HT"
    @short_standards = {}
    @short_standards["America/Anchorage"] = "HNAK"
    @short_standards["America/Chicago"] = "HNC (ÉUA)"
    @short_standards["America/Denver"] = "HNR (ÉUA)"
    @short_standards["America/Edmonton"] = "HNR"
    @short_standards["America/Halifax"] = "HNA"
    @short_standards["America/Indianapolis"] = "HNE (ÉUA)"
    @short_standards["America/Los_Angeles"] = "HNP (ÉUA)"
    @short_standards["America/Montreal"] = "HNE"
    @short_standards["America/New_York"] = "HNE (ÉUA)"
    @short_standards["America/Phoenix"] = "HNR (ÉUA)"
    @short_standards["America/St_Johns"] = "HNT"
    @short_standards["America/Vancouver"] = "HNP"
    @short_standards["America/Winnipeg"] = "HNC"
    @short_standards["Asia/Jerusalem"] = "HNI"
    @short_standards["Asia/Shanghai"] = "HNC"
    @short_standards["Asia/Tokyo"] = "HNJ"
    @short_standards["Europe/Bucharest"] = "HEE"
    @short_standards["Europe/Paris"] = "HNEC"
    @short_standards["Pacific/Honolulu"] = "HST"
    @short_daylights = {}
    @short_daylights["America/Anchorage"] = "HAAK"
    @short_daylights["America/Chicago"] = "HAC (ÉUA)"
    @short_daylights["America/Denver"] = "HAR (ÉUA)"
    @short_daylights["America/Edmonton"] = "HAR"
    @short_daylights["America/Halifax"] = "HAA"
    @short_daylights["America/Indianapolis"] = "HAE (ÉUA)"
    @short_daylights["America/Los_Angeles"] = "HAP (ÉUA)"
    @short_daylights["America/Montreal"] = "HAE"
    @short_daylights["America/New_York"] = "HAE (ÉUA)"
    @short_daylights["America/Phoenix"] = "HAR (ÉUA)"
    @short_daylights["America/St_Johns"] = "HAT"
    @short_daylights["America/Vancouver"] = "HAP"
    @short_daylights["America/Winnipeg"] = "HAC"
    @short_daylights["Asia/Jerusalem"] = "HAI"
    @short_daylights["Asia/Shanghai"] = "HAC"
    @short_daylights["Asia/Tokyo"] = "HAJ"
    @short_daylights["Europe/Bucharest"] = "HAEE"
    @short_daylights["Europe/Paris"] = "HAEC"
    @short_daylights["Pacific/Honolulu"] = "HDT"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
