#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/uz_Cyrl_UZ.xml
# Original file revision: 1.3 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["ar"] = "Арабча"
    @languages["de"] = "Олмонча"
    @languages["en"] = "Инглизча"
    @languages["es"] = "Испанча"
    @languages["fr"] = "Французча"
    @languages["hi"] = "Ҳиндча"
    @languages["it"] = "Италянча"
    @languages["ja"] = "Японча"
    @languages["pt"] = "Португалча"
    @languages["ru"] = "Русча"
    @languages["uz"] = "Ўзбек"
    @languages["zh"] = "Хитойча"
    @territories = {}
    @territories["AF"] = "Афғонистон"
    @territories["BR"] = "Бразилия"
    @territories["CN"] = "Хитой"
    @territories["DE"] = "Олмония"
    @territories["FR"] = "Франция"
    @territories["GB"] = "Бирлашган Қироллик"
    @territories["IN"] = "Ҳиндистон"
    @territories["IT"] = "Италия"
    @territories["JP"] = "Япония"
    @territories["RU"] = "Россия"
    @territories["US"] = "Қўшма Штатлар"
    @territories["UZ"] = "Ўзбекистон"
    @scripts = {}
    @scripts["Arab"] = "Араб"
    @scripts["Cyrl"] = "Кирил"
    @scripts["Latn"] = "Лотин"
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[а-яёіўѣѳѵҳ]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
