#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/sh_CS.xml
# Original file revision: 1.28 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HHmm;-HHmm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Kinshasa"] = "Kinšasa"
    @exemplarcities["Africa/Lubumbashi"] = "Лумумбаши"
    @exemplarcities["Antarctica/South_Pole"] = "Južni pol"
    @exemplarcities["Asia/Anadyr"] = "Anadir"
    @exemplarcities["Asia/Kamchatka"] = "Kamčatka"
    @exemplarcities["Asia/Krasnoyarsk"] = "Krasnojarsk"
    @exemplarcities["Asia/Shanghai"] = "Šangaj"
    @exemplarcities["Asia/Tashkent"] = "Taškent"
    @exemplarcities["Europe/Kiev"] = "Kijev"
    @exemplarcities["Europe/Moscow"] = "Moskva"
    @exemplarcities["Europe/Uzhgorod"] = "Užgorod"
    @exemplarcities["Europe/Zaporozhye"] = "Zaporožje"
    @long_generics = {}
    @long_standards = {}
    @long_standards["Europe/Belgrade"] = "Centralno Evropsko Vreme"
    @long_daylights = {}
    @long_daylights["Europe/Belgrade"] = "Centralno Evropsko Vreme"
    @short_generics = {}
    @short_standards = {}
    @short_standards["Europe/Belgrade"] = "CET"
    @short_daylights = {}
    @short_daylights["Europe/Belgrade"] = "CET"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
