#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/haw_US.xml
# Original file revision: 1.15 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["haw"] = "ʻōlelo Hawaiʻi"
    @territories = {}
    @territories["AU"] = "Nūhōlani"
    @territories["CA"] = "Kanakā"
    @territories["CN"] = "Kina"
    @territories["DE"] = "Kelemānia"
    @territories["DK"] = "Kenemaka"
    @territories["ES"] = "Kepania"
    @territories["FR"] = "Palani"
    @territories["GB"] = "Aupuni Mōʻī Hui Pū ʻIa"
    @territories["GR"] = "Helene"
    @territories["IE"] = "ʻIlelani"
    @territories["IL"] = "ʻIseraʻela"
    @territories["IN"] = "ʻĪnia"
    @territories["IT"] = "ʻĪkālia"
    @territories["JP"] = "Iāpana"
    @territories["MX"] = "Mekiko"
    @territories["NL"] = "Hōlani"
    @territories["NZ"] = "Aotearoa"
    @territories["PH"] = "ʻĀina Pilipino"
    @territories["RU"] = "Lūkia"
    @territories["US"] = "ʻAmelika Hui Pū ʻIa"
    @scripts = {}
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[āēīōūaeiouhklmnpwʻ]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "US"
    @measurement_papersize_height = "279"
    @measurement_papersize_width = "216"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
