#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/el_CY.xml
# Original file revision: 1.6 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HHmm;-HHmm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Bamako"] = "Μπαμάκο"
    @exemplarcities["Africa/Kinshasa"] = "Κινσάσα"
    @exemplarcities["Africa/Timbuktu"] = "Τιμπουκτού"
    @exemplarcities["America/Anchorage"] = "Άνκορατζ"
    @exemplarcities["America/Buenos_Aires"] = "Μπουένος Άιρες"
    @exemplarcities["America/Cancun"] = "Κανκούν"
    @exemplarcities["America/Chicago"] = "Σικάγο"
    @exemplarcities["America/Denver"] = "Ντένβερ"
    @exemplarcities["America/Detroit"] = "Ντητρόιτ"
    @exemplarcities["America/Indianapolis"] = "Ινδιανάπολη"
    @exemplarcities["America/Los_Angeles"] = "Λος Άντζελες"
    @exemplarcities["America/Manaus"] = "Μανάος"
    @exemplarcities["America/Mexico_City"] = "Πόλη του Μεξικού"
    @exemplarcities["America/Montreal"] = "Μόντρεαλ"
    @exemplarcities["America/New_York"] = "Νέα Υόρκη"
    @exemplarcities["America/Phoenix"] = "Φοίνιξ"
    @exemplarcities["America/Santiago"] = "Σαντιάγκο"
    @exemplarcities["America/Sao_Paulo"] = "Σάο Πάολο"
    @exemplarcities["America/Tijuana"] = "Τιχουάνα"
    @exemplarcities["America/Toronto"] = "Τορόντο"
    @exemplarcities["America/Vancouver"] = "Βανκούβερ"
    @exemplarcities["Asia/Irkutsk"] = "Ιρκούτσκ"
    @exemplarcities["Asia/Jakarta"] = "Τζακάρτα"
    @exemplarcities["Asia/Kuala_Lumpur"] = "Κουάλα Λουμπούρ"
    @exemplarcities["Asia/Novosibirsk"] = "Νοβοσιμπίρσκ"
    @exemplarcities["Asia/Omsk"] = "Ομσκ"
    @exemplarcities["Asia/Samarkand"] = "Σαμαρκάνδη"
    @exemplarcities["Asia/Shanghai"] = "Σανγκάη"
    @exemplarcities["Asia/Ulaanbaatar"] = "Ουλάν Μπατόρ"
    @exemplarcities["Asia/Vladivostok"] = "Βλαδιβοστόκ"
    @exemplarcities["Atlantic/Azores"] = "Αζόρες"
    @exemplarcities["Atlantic/Canary"] = "Κανάρια"
    @exemplarcities["Atlantic/Madeira"] = "Μαδέρα"
    @exemplarcities["Australia/Adelaide"] = "Αδελαΐδα"
    @exemplarcities["Australia/Melbourne"] = "Μελβούρνη"
    @exemplarcities["Australia/Sydney"] = "Σύδνεϊ"
    @exemplarcities["Europe/Belfast"] = "Μπέλφαστ"
    @exemplarcities["Europe/Kaliningrad"] = "Καλλίπολη"
    @exemplarcities["Europe/Kiev"] = "Κίεβο"
    @exemplarcities["Europe/Lisbon"] = "Λισσαβώνα"
    @exemplarcities["Europe/London"] = "Λονδίνο"
    @exemplarcities["Europe/Madrid"] = "Μαδρίτη"
    @exemplarcities["Europe/Moscow"] = "Μόσχα"
    @exemplarcities["Europe/Samara"] = "Σαμάρα"
    @exemplarcities["Pacific/Auckland"] = "Όκλαντ"
    @exemplarcities["Pacific/Galapagos"] = "Γκαλαπάγκος"
    @exemplarcities["Pacific/Honolulu"] = "Χονολουλού"
    @exemplarcities["Pacific/Tahiti"] = "Αϊτή"
    @long_generics = {}
    @long_standards = {}
    @long_daylights = {}
    @short_generics = {}
    @short_standards = {}
    @short_daylights = {}
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
