#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/ga_IE.xml
# Original file revision: 1.26 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Europe/Belfast"] = "Béal Feirste"
    @exemplarcities["Europe/Dublin"] = "Baile Átha Cliath"
    @exemplarcities["Europe/London"] = "Londain"
    @long_generics = {}
    @long_standards = {}
    @long_standards["Europe/Belfast"] = "Meán-Am Greenwich"
    @long_standards["Europe/Dublin"] = "Meán-Am Greenwich"
    @long_standards["Europe/London"] = "Meán-Am Greenwich"
    @long_daylights = {}
    @long_daylights["Europe/Belfast"] = "Am Samhraidh na Breataine"
    @long_daylights["Europe/Dublin"] = "Am Samhraidh na hÉireann"
    @long_daylights["Europe/London"] = "Am Samhraidh na Breataine"
    @short_generics = {}
    @short_standards = {}
    @short_standards["Europe/Belfast"] = "MAG"
    @short_standards["Europe/Dublin"] = "MAG"
    @short_standards["Europe/London"] = "MAG"
    @short_daylights = {}
    @short_daylights["Europe/Belfast"] = "ASB"
    @short_daylights["Europe/Dublin"] = "ASÉ"
    @short_daylights["Europe/London"] = "ASB"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
