#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/dz_BT.xml
# Original file revision: 1.18 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["ar"] = "ཨེ་ར་སྦིག"
    @languages["art"] = "བཟོ་བཟོཝ (གཞན)"
    @languages["as"] = "ཨ་ས་མི་སི"
    @languages["bh"] = "བི་ཧ་ལི"
    @languages["bn"] = "བེངྒ་ལི"
    @languages["bo"] = "བོད་ཁ"
    @languages["cs"] = "ཅེཀ"
    @languages["da"] = "ཌེ་ནིཤ"
    @languages["de"] = "ཇཱར་མཱན"
    @languages["dv"] = "དི་བེ་ཧི"
    @languages["dz"] = "རྫོང་ཁ"
    @languages["egy"] = "ཨི་ཇིཔ་ཤཱན (སྔ་དུས་ཀྱི)"
    @languages["el"] = "གིརིཀ"
    @languages["en"] = "ཨིང་ལིཤ"
    @languages["es"] = "སིཔེ་ནིཤ"
    @languages["fa"] = "པར་ཤི་ཡན"
    @languages["fr"] = "ཕེ་རེནཆེ"
    @languages["ga"] = "ཨའི་རིཤ"
    @languages["grc"] = "གིརིཀ, སྔ་དུས་ཀྱི (༡༤༥༣)"
    @languages["he"] = "ཧི་བུརུ"
    @languages["hi"] = "ཧིན་དི"
    @languages["him"] = "ཧི་མ་ཅ་ལི"
    @languages["inc"] = "ཨིན་ཌིཀ (གཞན)"
    @languages["it"] = "ཨི་ཊ་ལི་རན"
    @languages["km"] = "ཁེ་མར"
    @languages["kn"] = "ཀ་ན་ཌ"
    @languages["ko"] = "ཀོ་རིཡན"
    @languages["ks"] = "ཀེཤ་མི་རི"
    @languages["lo"] = "ལའོ"
    @languages["ml"] = "མ་ལ་ཡ་ལམ"
    @languages["mn"] = "སོག་པོའི་ཁ"
    @languages["mnc"] = "མཱན་ཅུ"
    @languages["mni"] = "མ་ནི་པུ་རི"
    @languages["mr"] = "མ་ར་ཐི"
    @languages["my"] = "བར་མིསི"
    @languages["ne"] = "ནེ་པ་ལི"
    @languages["new"] = "ནི་ཝ་རི"
    @languages["nl"] = "ཌཆ"
    @languages["no"] = "ནོར་ཝི་ཇི་ཡན"
    @languages["or"] = "ཨོ་རི་ཡ"
    @languages["pa"] = "པཱན་ཇ་བི"
    @languages["pi"] = "པ་ལི"
    @languages["ru"] = "ར་ཤི་ཡན"
    @languages["sa"] = "སཾསྐྲྀཏ"
    @languages["si"] = "སིན་ཧ་ལིསི"
    @languages["ta"] = "ཏ་མིལ"
    @languages["te"] = "ཏེ་ལུ་གུ"
    @languages["th"] = "ཐཱའེ"
    @languages["ur"] = "ཨུར་དུ"
    @languages["zh"] = "རགྱ་མི་ཁ"
    @territories = {}
    @territories["AE"] = "ཡུ་ནའི་ཊེཊ་ཨ་ར བ་ཨེ་མི་རེཊསི"
    @territories["AF"] = "ཨཕ་ག་ནིསི་ཏཱན"
    @territories["AQ"] = "ཨེན་ཊཱག་ཊི་ཀ"
    @territories["AR"] = "ཨར་ཇེན་ཊི་ན"
    @territories["AT"] = "ཨས་ཊི་ཡ"
    @territories["AU"] = "ཨས་ཊེཡེ་ལི་ཡ"
    @territories["BD"] = "བངྒ་ལ་དེཤ"
    @territories["BE"] = "བེལ་ཇིཡམ"
    @territories["BH"] = "བཧ་རེན"
    @territories["BR"] = "བཱརཱ་ཛིལ"
    @territories["BT"] = "འབྲུག"
    @territories["CA"] = "ཀེ་ན་ཌ"
    @territories["CH"] = "སུའིཊ་ཛར་ལེན"
    @territories["CN"] = "རྒྱ་མི"
    @territories["CU"] = "ཀིའུ་སྦ"
    @territories["CZ"] = "ཅེཀ་རི་པབ་ལིཀ"
    @territories["DE"] = "ཇཱར་མ་ནི"
    @territories["DK"] = "ཌེན་མཱཀ"
    @territories["EG"] = "ཨི་ཇིཔཊ"
    @territories["ES"] = "སིཔཱེན"
    @territories["FI"] = "ཕིན་ལེནཌ"
    @territories["FR"] = "ཕརཱནསི"
    @territories["GB"] = "ཡུ་ནའི་ཊེཊ་ཀིང་ཌམ"
    @territories["GR"] = "གིརིསི"
    @territories["HK"] = "ཧོང་ཀོང"
    @territories["IE"] = "ཨའིརི་ལེནཌ"
    @territories["IL"] = "ཨིཛ་རཱེལ"
    @territories["IN"] = "རྒྱ་གར"
    @territories["IQ"] = "ཨི་རཀ"
    @territories["IR"] = "ཨི་རཱན"
    @territories["IS"] = "ཨའིསི་ལེནཌ"
    @territories["IT"] = "ཨྀཊ་ལི"
    @territories["JM"] = "ཇ་མའི་ཀ"
    @territories["JP"] = "ཇ་པཱན"
    @territories["KE"] = "ཀེ་ནི་ཡ"
    @territories["KH"] = "ཀམ་བོ་ཌི་ཡ"
    @territories["KP"] = "བྱང་ཀོ་རི་ཡ"
    @territories["KR"] = "ལྷོ་ཀོ་རི་ཡ"
    @territories["KW"] = "ཀུ་ཝེཊ"
    @territories["LA"] = "ལ་འོསུ"
    @territories["LB"] = "ལེ་བཱ་ནཱོན"
    @territories["LK"] = "ཤྲཱྀ་ལངཀ"
    @territories["MM"] = "མེ་མར"
    @territories["MN"] = "སོག་པོ"
    @territories["MS"] = "མོན་ས་རཊི"
    @territories["MU"] = "མོ་རི་ཤིཡསི"
    @territories["MV"] = "མཱལ་ཌིབས"
    @territories["MX"] = "མེཀསི་ཀོ"
    @territories["MY"] = "མ་ལེ་ཤི་ཡ"
    @territories["NL"] = "ནེ་དར་ལེནཌསི"
    @territories["NO"] = "ནོ་ཝེ"
    @territories["NP"] = "བལ་ཡུལ"
    @territories["NZ"] = "ནིའུ་ཛི་ལེནཌ"
    @territories["PA"] = "པ་ན་མཱ"
    @territories["PK"] = "པ་ཀིསི་ཏཱན"
    @territories["PS"] = "པེ་ལིསི་ཊི་ནིཡ ན་ཊེ་རི་ངོ་རི"
    @territories["PT"] = "པོར་ཅུ་གལ"
    @territories["QA"] = "ཀ་ཏར"
    @territories["SA"] = "སའུ་དི་ཨེ་ར་ས ྦི་ཡ"
    @territories["SE"] = "སུའི་ཌན"
    @territories["SI"] = "སིལོ་བེ་ནི་ཡ"
    @territories["TH"] = "ཐཱའི་ལེནཌ"
    @territories["TJ"] = "ཏ་ཇག་ཀིསི་ཏཱན"
    @territories["TW"] = "ཏའི་ཝཱན"
    @territories["US"] = "ཡུ་ནའིཊེཊ་སི་ཊེསི"
    @territories["UZ"] = "ཨུཛ་བེ་ཀིསི་ཏཱན"
    @territories["VN"] = "བེཊ་ནཱམ"
    @territories["ZA"] = "སའུཐ་ཨཕ་རི་ཀ"
    @territories["ZM"] = "ཛམ་བི་ཡ"
    @territories["ZW"] = "ཛིམ་བབ་ཝེ"
    @scripts = {}
    @scripts["Arab"] = "ཨེ་རེ་སྦིག"
    @scripts["Beng"] = "བེངྒ་ལི"
    @scripts["Brai"] = "བེརེལ"
    @scripts["Cyrl"] = "སིརི་ལིཀ"
    @scripts["Deva"] = "དི་ཝ་ན་གརི"
    @scripts["Grek"] = "གིརིཀ"
    @scripts["Gujr"] = "གུ་ཇ་ར་ཏི"
    @scripts["Guru"] = "གུར་མུ་ཁི"
    @scripts["Hang"] = "ཧང་གུལ"
    @scripts["Hani"] = "ཧཱན"
    @scripts["Hans"] = "ལུགས་གསར ཧཱན"
    @scripts["Hant"] = "ལུགས་རྙིང ཧཱན"
    @scripts["Hebr"] = "ཧི་བུརུ"
    @scripts["Hira"] = "ཧི་ར་ག་ན"
    @scripts["Kana"] = "ཀ་ཏ་ཀ་ན"
    @scripts["Khmr"] = "ཁེ་མར"
    @scripts["Knda"] = "ཀ་ན་ཌ"
    @scripts["Laoo"] = "ལའོ"
    @scripts["Latn"] = "ལེ་ཊིན"
    @scripts["Limb"] = "ལིམ་བུ"
    @scripts["Mlym"] = "མ་ལ་ཡ་ལམ"
    @scripts["Mong"] = "སོག་པོ"
    @scripts["Mymr"] = "མི་མར"
    @scripts["Orya"] = "ཨོ་རི་ཡ"
    @scripts["Qaai"] = "སྔར་རྒྱུན"
    @scripts["Sinh"] = "སིན་ཧ་ལ"
    @scripts["Taml"] = "ཏ་མིལ"
    @scripts["Telu"] = "ཏེ་ལུ་གུ"
    @scripts["Thaa"] = "ཐཱ་ན"
    @scripts["Tibt"] = "བོད"
    @scripts["Zyyy"] = "སྤྱིར"
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[ཀཁགངཅཆཇཉཏཐདནཔཕབམཙཚཛཝཞཟའཡརལཤསཧཨཱིེོུྐྒྔྕྗྙྟྡྣྤྦྨྩྫྭྱྲླྷ]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @character_mapping|utf-8 = "iana"
    @delimiter_quotation_start = """
    @delimiter_quotation_end = """
    @delimiter_alternate_quotation_start = "'"
    @delimiter_alternate_quotation_end = "'"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @keys["collation"] = "གནས་སདུད་རིམ་ སགྲིག"
    @types = {}
    @types["traditional"] = "ལུགས་སྲོལ"
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping|utf-8
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
