#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/dz_BT.xml
# Original file revision: 1.18 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Asia/Thimphu"] = "ཐིམ་ཕུག"
    @long_generics = {}
    @long_generics["Asia/Thimphu"] = "Bhutan Standard Time"
    @long_standards = {}
    @long_standards["Asia/Thimphu"] = "Bhutan Standard Time"
    @long_daylights = {}
    @long_daylights["Asia/Thimphu"] = "Bhutan Standard Time"
    @short_generics = {}
    @short_generics["Asia/Thimphu"] = "BST"
    @short_standards = {}
    @short_standards["Asia/Thimphu"] = "BST"
    @short_daylights = {}
    @short_daylights["Asia/Thimphu"] = "BST"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
