#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/sk_SK.xml
# Original file revision: 1.27 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HHmm;-HHmm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Antarctica/South_Pole"] = "Južný pól"
    @exemplarcities["Asia/Irkutsk"] = "Irkutsko"
    @exemplarcities["Asia/Kamchatka"] = "Kamčatka"
    @exemplarcities["Asia/Krasnoyarsk"] = "Krasnojarsko"
    @exemplarcities["Asia/Sakhalin"] = "Sachalin"
    @exemplarcities["Asia/Shanghai"] = "Šanghaj"
    @exemplarcities["Asia/Tashkent"] = "Taškent"
    @exemplarcities["Asia/Ulaanbaatar"] = "Ulanbátar"
    @exemplarcities["Asia/Yakutsk"] = "Jakutsko"
    @exemplarcities["Asia/Yekaterinburg"] = "Jekaterinburg"
    @exemplarcities["Atlantic/Azores"] = "Azorské ostrovy"
    @exemplarcities["Atlantic/Canary"] = "Kanárske ostrovy"
    @exemplarcities["Europe/Kiev"] = "Kyjev"
    @exemplarcities["Europe/Lisbon"] = "Lisabon"
    @exemplarcities["Europe/London"] = "Londýn"
    @exemplarcities["Europe/Moscow"] = "Moskva"
    @exemplarcities["Europe/Uzhgorod"] = "Užhorod"
    @exemplarcities["Europe/Zaporozhye"] = "Záporožie"
    @exemplarcities["Pacific/Galapagos"] = "Galapágy"
    @long_generics = {}
    @long_standards = {}
    @long_daylights = {}
    @short_generics = {}
    @short_standards = {}
    @short_daylights = {}
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
