#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/ko.xml
# Original file revision: 1.51 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Casablanca"] = "카사블랑카"
    @exemplarcities["America/Anchorage"] = "앵커리지"
    @exemplarcities["America/Chicago"] = "시카고"
    @exemplarcities["America/Denver"] = "덴버"
    @exemplarcities["America/Halifax"] = "핼리팩스"
    @exemplarcities["America/Indianapolis"] = "인디애나폴리스"
    @exemplarcities["America/Los_Angeles"] = "로스앤젤레스"
    @exemplarcities["America/New_York"] = "뉴욕"
    @exemplarcities["America/Phoenix"] = "피닉스"
    @exemplarcities["America/St_Johns"] = "St. Johns"
    @exemplarcities["Asia/Jerusalem"] = "예루살렘"
    @exemplarcities["Asia/Seoul"] = "서울"
    @exemplarcities["Asia/Shanghai"] = "상하이"
    @exemplarcities["Asia/Tokyo"] = "도쿄"
    @exemplarcities["Europe/Bucharest"] = "부쿠레슈티"
    @exemplarcities["Europe/Paris"] = "파리"
    @exemplarcities["Pacific/Honolulu"] = "호놀룰루"
    @long_generics = {}
    @long_standards = {}
    @long_standards["Africa/Casablanca"] = "그리니치 표준시"
    @long_standards["America/Anchorage"] = "알래스카 표준시"
    @long_standards["America/Chicago"] = "중부 표준시"
    @long_standards["America/Denver"] = "산악 표준시"
    @long_standards["America/Halifax"] = "대서양 표준시"
    @long_standards["America/Indianapolis"] = "동부 표준시"
    @long_standards["America/Los_Angeles"] = "태평양 표준시"
    @long_standards["America/New_York"] = "동부 표준시"
    @long_standards["America/Phoenix"] = "산악 표준시"
    @long_standards["America/St_Johns"] = "뉴펀들랜드 표준시"
    @long_standards["Asia/Jerusalem"] = "이스라엘 표준시"
    @long_standards["Asia/Seoul"] = "한국표준시"
    @long_standards["Asia/Shanghai"] = "중국 표준시"
    @long_standards["Asia/Tokyo"] = "일본 표준시"
    @long_standards["Europe/Bucharest"] = "동부유럽 표준시"
    @long_standards["Europe/Paris"] = "중부유럽 표준시"
    @long_standards["Pacific/Honolulu"] = "하와이 표준시"
    @long_daylights = {}
    @long_daylights["Africa/Casablanca"] = "그리니치 표준시"
    @long_daylights["America/Anchorage"] = "알래스카 기준시"
    @long_daylights["America/Chicago"] = "중부 기준시"
    @long_daylights["America/Denver"] = "산악 기준시"
    @long_daylights["America/Halifax"] = "대서양 기준시"
    @long_daylights["America/Indianapolis"] = "동부 표준시"
    @long_daylights["America/Los_Angeles"] = "태평양 기준시"
    @long_daylights["America/New_York"] = "동부 기준시"
    @long_daylights["America/Phoenix"] = "산악 표준시"
    @long_daylights["America/St_Johns"] = "뉴펀들랜드 기준시"
    @long_daylights["Asia/Jerusalem"] = "이스라엘 기준시"
    @long_daylights["Asia/Seoul"] = "한국표준시"
    @long_daylights["Asia/Shanghai"] = "중국 표준시"
    @long_daylights["Asia/Tokyo"] = "일본 표준시"
    @long_daylights["Europe/Bucharest"] = "동부유럽 기준시"
    @long_daylights["Europe/Paris"] = "중부유럽 기준시"
    @long_daylights["Pacific/Honolulu"] = "하와이 표준시"
    @short_generics = {}
    @short_standards = {}
    @short_standards["Africa/Casablanca"] = "GMT"
    @short_standards["America/Anchorage"] = "AST"
    @short_standards["America/Chicago"] = "CST"
    @short_standards["America/Denver"] = "MST"
    @short_standards["America/Halifax"] = "AST"
    @short_standards["America/Indianapolis"] = "EST"
    @short_standards["America/Los_Angeles"] = "PST"
    @short_standards["America/New_York"] = "EST"
    @short_standards["America/Phoenix"] = "MST"
    @short_standards["America/St_Johns"] = "CNT"
    @short_standards["Asia/Jerusalem"] = "IST"
    @short_standards["Asia/Seoul"] = "KST"
    @short_standards["Asia/Shanghai"] = "CTT"
    @short_standards["Asia/Tokyo"] = "JST"
    @short_standards["Europe/Bucharest"] = "EET"
    @short_standards["Europe/Paris"] = "CET"
    @short_standards["Pacific/Honolulu"] = "HST"
    @short_daylights = {}
    @short_daylights["Africa/Casablanca"] = "GMT"
    @short_daylights["America/Anchorage"] = "ADT"
    @short_daylights["America/Chicago"] = "CDT"
    @short_daylights["America/Denver"] = "MDT"
    @short_daylights["America/Halifax"] = "ADT"
    @short_daylights["America/Indianapolis"] = "EST"
    @short_daylights["America/Los_Angeles"] = "PDT"
    @short_daylights["America/New_York"] = "EDT"
    @short_daylights["America/Phoenix"] = "MST"
    @short_daylights["America/St_Johns"] = "CDT"
    @short_daylights["Asia/Jerusalem"] = "IDT"
    @short_daylights["Asia/Seoul"] = "KST"
    @short_daylights["Asia/Shanghai"] = "CDT"
    @short_daylights["Asia/Tokyo"] = "JST"
    @short_daylights["Europe/Bucharest"] = "EEST"
    @short_daylights["Europe/Paris"] = "CEST"
    @short_daylights["Pacific/Honolulu"] = "HST"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
