#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/be.xml
# Original file revision: 1.35 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["ar"] = "арабскі"
    @languages["be"] = "Беларускі"
    @languages["de"] = "нямецкі"
    @languages["en"] = "англійскі"
    @languages["es"] = "іспанскі"
    @languages["fr"] = "французскі"
    @languages["hi"] = "хіндзі"
    @languages["it"] = "італьянскі"
    @languages["ja"] = "японскі"
    @languages["pt"] = "партугальскі"
    @languages["ru"] = "рускі"
    @languages["zh"] = "кітайскі"
    @territories = {}
    @territories["BR"] = "Бразілія"
    @territories["BY"] = "Беларусь"
    @territories["CN"] = "Кітай"
    @territories["DE"] = "Германія"
    @territories["FR"] = "Францыя"
    @territories["GB"] = "Велікабрытанія"
    @territories["IN"] = "Індыя"
    @territories["IT"] = "Італія"
    @territories["JP"] = "Японія"
    @territories["RU"] = "Расія"
    @territories["US"] = "Злучаныя Штаты"
    @scripts = {}
    @scripts["Cyrl"] = "кірылічны"
    @scripts["Latn"] = "лацінскі"
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[а-з й-ш ы-я ’ёіў {дж} {дз}]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "так:т"
    @nostr = "не:н"
    @yesexpr = "^([yY]([eE][sS])?)|([тТ]([аА][кК])?)"
    @noexpr = "^([nN][oO]?)|([нН][еЕ]?)"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
