#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/mr_IN.xml
# Original file revision: 1.34 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["aa"] = "अफार"
    @languages["ab"] = "अबखेजियन"
    @languages["af"] = "अफ्रिकान्स"
    @languages["am"] = "अमहारिक"
    @languages["ar"] = "अरेबिक"
    @languages["as"] = "असामी"
    @languages["ay"] = "ऐमरा"
    @languages["az"] = "अज़रबाइजानी"
    @languages["ba"] = "बष्किर"
    @languages["be"] = "बैलोरुसियन"
    @languages["bg"] = "बल्गेरियन"
    @languages["bh"] = "बीहारी"
    @languages["bi"] = "बिसलमा"
    @languages["bn"] = "बंगाली"
    @languages["bo"] = "तिबेटियन"
    @languages["br"] = "ब्रेटन"
    @languages["ca"] = "कटलन"
    @languages["co"] = "कोर्सिकन"
    @languages["cs"] = "ज़ेक"
    @languages["cy"] = "वेल्ष"
    @languages["da"] = "डानिष"
    @languages["de"] = "जर्मन"
    @languages["dz"] = "भूटानी"
    @languages["el"] = "ग्रीक"
    @languages["en"] = "इंग्रेजी"
    @languages["eo"] = "इस्परान्टो"
    @languages["es"] = "स्पानिष"
    @languages["et"] = "इस्टोनियन्"
    @languages["eu"] = "बास्क"
    @languages["fa"] = "पर्षियन्"
    @languages["fi"] = "फिन्निष"
    @languages["fj"] = "फिजी"
    @languages["fo"] = "फेरोस्"
    @languages["fr"] = "फ्रेन्च"
    @languages["fy"] = "फ्रिसियन्"
    @languages["ga"] = "ऐरिष"
    @languages["gd"] = "स्काटस् गेलिक"
    @languages["gl"] = "गेलीशियन"
    @languages["gn"] = "गौरानी"
    @languages["gu"] = "गुजराती"
    @languages["ha"] = "हौसा"
    @languages["he"] = "हेबृ"
    @languages["hi"] = "हिन्दी"
    @languages["hr"] = "क्रोयेषियन्"
    @languages["hu"] = "हंगेरियन्"
    @languages["hy"] = "आर्मीनियन्"
    @languages["ia"] = "इन्टरलिंग्वा"
    @languages["id"] = "इन्डोनेषियन"
    @languages["ie"] = "इन्टरलिंग"
    @languages["ik"] = "इनूपियाक"
    @languages["is"] = "आईसलान्डिक"
    @languages["it"] = "इटालियन"
    @languages["iu"] = "इनुकिटुट्"
    @languages["ja"] = "जापनीस्"
    @languages["jv"] = "जावनीस्"
    @languages["ka"] = "जार्जियन्"
    @languages["kk"] = "कज़क"
    @languages["kl"] = "ग्रीनलान्डिक"
    @languages["km"] = "कंबोडियन"
    @languages["kn"] = "कन्नड"
    @languages["ko"] = "कोरियन्"
    @languages["kok"] = "कोंकणी"
    @languages["ks"] = "कश्मीरी"
    @languages["ku"] = "कुर्दिष"
    @languages["ky"] = "किर्गिज़"
    @languages["la"] = "लाटिन"
    @languages["ln"] = "लिंगाला"
    @languages["lo"] = "लाओतियन्"
    @languages["lt"] = "लिथुआनियन्"
    @languages["lv"] = "लाट्वियन् (लेट्टिष)"
    @languages["mg"] = "मलागसी"
    @languages["mi"] = "माओरी"
    @languages["mk"] = "मसीडोनियन्"
    @languages["ml"] = "मलियालम"
    @languages["mn"] = "मंगोलियन्"
    @languages["mo"] = "मोल्डावियन्"
    @languages["mr"] = "मराठी"
    @languages["ms"] = "मलय"
    @languages["mt"] = "मालतीस्"
    @languages["my"] = "बर्मीस्"
    @languages["na"] = "नौरो"
    @languages["ne"] = "नेपाली"
    @languages["nl"] = "डच"
    @languages["no"] = "नोर्वेजियन"
    @languages["oc"] = "ओसिटान्"
    @languages["om"] = "ओरोमो (अफान)"
    @languages["or"] = "ओरिया"
    @languages["pa"] = "पंजाबी"
    @languages["pl"] = "पोलिष"
    @languages["ps"] = "पष्टो (पुष्टो)"
    @languages["pt"] = "पोर्चुगीस्"
    @languages["qu"] = "क्वेचओ"
    @languages["rm"] = "रहटो-रोमान्स्"
    @languages["rn"] = "किरुन्दी"
    @languages["ro"] = "रोमानियन्"
    @languages["root"] = "मराठी"
    @languages["ru"] = "रष्यन्"
    @languages["rw"] = "किन्यार्वान्डा"
    @languages["sa"] = "संस्कृत"
    @languages["sd"] = "सिंधी"
    @languages["sg"] = "सांग्रो"
    @languages["sh"] = "सेर्बो-क्रोयेषियन्"
    @languages["si"] = "सिन्हलीस्"
    @languages["sk"] = "स्लोवाक"
    @languages["sl"] = "स्लोवेनियन्"
    @languages["sm"] = "समोन"
    @languages["sn"] = "शोना"
    @languages["so"] = "सोमाली"
    @languages["sq"] = "आल्बेनियन्"
    @languages["sr"] = "सेर्बियन्"
    @languages["ss"] = "सिस्वती"
    @languages["st"] = "सेसोथो"
    @languages["su"] = "सुंदनीस्"
    @languages["sv"] = "स्वीडिष"
    @languages["sw"] = "स्वाहिली"
    @languages["ta"] = "तमिळ"
    @languages["te"] = "तेलंगू"
    @languages["tg"] = "तजिक"
    @languages["th"] = "थाई"
    @languages["ti"] = "तिग्रिन्या"
    @languages["tk"] = "तुर्कमेन"
    @languages["tl"] = "तगालोग"
    @languages["tn"] = "सेत्स्वाना"
    @languages["to"] = "तोंगा"
    @languages["tr"] = "तुर्किष"
    @languages["ts"] = "त्सोगा"
    @languages["tt"] = "टटार"
    @languages["tw"] = "त्वि"
    @languages["ug"] = "उधूर"
    @languages["uk"] = "युक्रेनियन्"
    @languages["ur"] = "उर्दू"
    @languages["uz"] = "उज़बेक"
    @languages["vi"] = "वियत्नामीज़"
    @languages["vo"] = "ओलापुक"
    @languages["wo"] = "उलोफ"
    @languages["xh"] = "क्स्होसा"
    @languages["yi"] = "इद्दिष"
    @languages["yo"] = "यूरुबा"
    @languages["za"] = "झ्हुन्ग"
    @languages["zh"] = "चिनीस्"
    @languages["zu"] = "जुलू"
    @territories = {}
    @territories["IN"] = "भारत"
    @scripts = {}
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[ँ-ह़-्ॐ-॔ॠ-ॣ०-९ॽ‌‍]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "'"
    @delimiter_quotation_end = "'"
    @delimiter_alternate_quotation_start = """
    @delimiter_alternate_quotation_end = """
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "हां"
    @nostr = "ना"
    @yesexpr = "^([yY]([eE][sS])?)|हां"
    @noexpr = "^([nN][oO]?)|ना"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
