#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/sr_YU.xml
# Original file revision: 1.27 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @format = "¤ #,##0.00"
    @before_match = "[:letter:]"
    @before_match_surrounding = "[:digit:]"
    @before_insertbetween = " "
    @after_match = "[:letter:]"
    @after_match_surrounding = "[:digit:]"
    @after_insertbetween = " "
    @currencies = {}
    @currencies["ATS"] = "Аустријски шилинг"
    @currencies["AUD"] = "Аустралијски долар"
    @currencies["BAM"] = "Конвертибилна марка"
    @currencies["BEF"] = "Белгијски франак"
    @currencies["BRL"] = "Бразилски Реал"
    @currencies["CAD"] = "Канадски долар"
    @currencies["CHF"] = "Швајцарски франак"
    @currencies["CNY"] = "Кинески Јуан Ренминби"
    @currencies["CSD"] = "Српски Динар"
    @currencies["DEM"] = "Немачка марка"
    @currencies["DKK"] = "Данска круна"
    @currencies["ESP"] = "Шпанска пезета"
    @currencies["EUR"] = "ЕВРО"
    @currencies["FIM"] = "Финска марка"
    @currencies["FRF"] = "Француски франак"
    @currencies["GBP"] = "Фунта стерлинга"
    @currencies["GRD"] = "Драхма"
    @currencies["HRD"] = "Хрватски динар"
    @currencies["HRK"] = "Куна"
    @currencies["IEP"] = "Ирска фунта"
    @currencies["INR"] = "Индијски Рупи"
    @currencies["ITL"] = "Италијанска лира"
    @currencies["JPY"] = "Јен"
    @currencies["KWD"] = "Кувајтски динар"
    @currencies["LUF"] = "Луксембуршки франак"
    @currencies["NLG"] = "Холандски гулден"
    @currencies["NOK"] = "Норвешка круна"
    @currencies["PTE"] = "Португалски ескудо"
    @currencies["RUB"] = "Руска рубља"
    @currencies["RUR"] = "Руска рубља (1991-1998)"
    @currencies["SEK"] = "Шведска круна"
    @currencies["SIT"] = "Толар"
    @currencies["USD"] = "Амерички долар"
    @symbols = {}
    @symbols["AUD"] = "$A"
    @symbols["BAM"] = "KM"
    @symbols["BEF"] = "BF"
    @symbols["BRL"] = "R$"
    @symbols["CAD"] = "Can$"
    @symbols["CHF"] = "SwF"
    @symbols["CNY"] = "Y"
    @symbols["CSD"] = "CSD"
    @symbols["DKK"] = "DKr"
    @symbols["EUR"] = "€"
    @symbols["GBP"] = "£"
    @symbols["IEP"] = "IR£"
    @symbols["INR"] = "INR"
    @symbols["ITL"] = "₤"
    @symbols["JPY"] = "¥"
    @symbols["KWD"] = "KD"
    @symbols["NOK"] = "NKr"
    @symbols["SEK"] = "SKr"
    @symbols["USD"] = "US$"
    @symbols["YUN"] = "Дин"
  end

  public
  attr_reader :format
  attr_reader :before_match
  attr_reader :before_match_surrounding
  attr_reader :before_insertbetween
  attr_reader :after_match
  attr_reader :after_match_surrounding
  attr_reader :after_insertbetween
  attr_reader :currencies
  attr_reader :symbols
