#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/fo.xml
# Original file revision: 1.26 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["fo"] = "føroyskt"
    @territories = {}
    @territories["AE"] = "Sameindu Emirríkini"
    @territories["AF"] = "Afganistan"
    @territories["AG"] = "Antigua og Barbuda"
    @territories["AQ"] = "Antarktis"
    @territories["AT"] = "Eysturríki"
    @territories["AU"] = "Avstralia"
    @territories["AZ"] = "Aserbajdsjan"
    @territories["BA"] = "Bosnia-Hersegovina"
    @territories["BD"] = "Bangladesj"
    @territories["BE"] = "Belgia"
    @territories["BR"] = "Brasilia"
    @territories["BT"] = "Butan"
    @territories["BW"] = "Botsvana"
    @territories["BY"] = "Hvítarussland"
    @territories["BZ"] = "Belis"
    @territories["CA"] = "Kanada"
    @territories["CF"] = "Miðafrikalýðveldið"
    @territories["CG"] = "Kongo"
    @territories["CH"] = "Sveis"
    @territories["CI"] = "Fílabeinsstrondin"
    @territories["CL"] = "Kili"
    @territories["CM"] = "Kamerun"
    @territories["CN"] = "Kina"
    @territories["CO"] = "Kolombia"
    @territories["CR"] = "Kosta Rika"
    @territories["CU"] = "Kuba"
    @territories["CV"] = "Grønhøvdaoyggjarnar"
    @territories["CY"] = "Kýpros"
    @territories["CZ"] = "Kekkia"
    @territories["DE"] = "Týskland"
    @territories["DK"] = "Danmørk"
    @territories["DM"] = "Dominika"
    @territories["DO"] = "Domingo lýðveldið"
    @territories["EC"] = "Ekvador"
    @territories["EE"] = "Estland"
    @territories["EG"] = "Egyptaland"
    @territories["ES"] = "Spania"
    @territories["ET"] = "Etiopia"
    @territories["FI"] = "Finnland"
    @territories["FM"] = "Mikronesia"
    @territories["FO"] = "Føroyar"
    @territories["FR"] = "Frakland"
    @territories["GQ"] = "Ekvator Guinea"
    @territories["GR"] = "Grikkaland"
    @territories["GW"] = "Guinea Bissau"
    @territories["GY"] = "Gujana"
    @territories["HR"] = "Kroatia"
    @territories["HU"] = "Ungarn"
    @territories["IE"] = "Írland"
    @territories["IL"] = "Ísrael"
    @territories["IQ"] = "Irak"
    @territories["IS"] = "Ísland"
    @territories["IT"] = "Italia"
    @territories["JM"] = "Jameika"
    @territories["KE"] = "Kenja"
    @territories["KG"] = "Kirgisia"
    @territories["KH"] = "Kambodja"
    @territories["KM"] = "Komorooyggjarnar"
    @territories["KN"] = "Saint Kitts og Nevis"
    @territories["KP"] = "Norður-Korea"
    @territories["KR"] = "Suður-Korea"
    @territories["KW"] = "Kuvait"
    @territories["KZ"] = "Kasakstan"
    @territories["LB"] = "Libanon"
    @territories["LC"] = "Saint Lusia"
    @territories["LI"] = "Liktenstein"
    @territories["LS"] = "Lesoto"
    @territories["LT"] = "Litava"
    @territories["LU"] = "Luksemborg"
    @territories["LV"] = "Lettland"
    @territories["MA"] = "Marokko"
    @territories["MC"] = "Monako"
    @territories["MG"] = "Madagaskar"
    @territories["MH"] = "Marshalloyggjarnar"
    @territories["MK"] = "Makedónia"
    @territories["MR"] = "Móritania"
    @territories["MU"] = "Móritius"
    @territories["MV"] = "Maldivuoyggjarnar"
    @territories["MW"] = "Malavi"
    @territories["MX"] = "Meksiko"
    @territories["MY"] = "Maleisia"
    @territories["MZ"] = "Mosambik"
    @territories["NI"] = "Nikaragua"
    @territories["NL"] = "Niðurlond"
    @territories["NO"] = "Noreg"
    @territories["NZ"] = "Ný Sæland"
    @territories["PE"] = "Perú"
    @territories["PG"] = "Papua Nýguinea"
    @territories["PH"] = "Filipsoyggjar"
    @territories["PL"] = "Pólland"
    @territories["PY"] = "Paraguei"
    @territories["QA"] = "Katar"
    @territories["RO"] = "Rumenia"
    @territories["RU"] = "Russland"
    @territories["RW"] = "Ruanda"
    @territories["SA"] = "Saudi-Arábia"
    @territories["SB"] = "Sálomonoyggjarnar"
    @territories["SC"] = "Seyskelloyggjarnar"
    @territories["SE"] = "Svøríki"
    @territories["SG"] = "Singapor"
    @territories["SR"] = "Surinam"
    @territories["ST"] = "Sao Tome og Prinsipi"
    @territories["SZ"] = "Svasiland"
    @territories["TD"] = "Kjad"
    @territories["TJ"] = "Tadsjikistan"
    @territories["TN"] = "Tunesia"
    @territories["TR"] = "Turkaland"
    @territories["TT"] = "Trinidad og Tobago"
    @territories["TW"] = "Teivan"
    @territories["TZ"] = "Tansania"
    @territories["UA"] = "Ukreina"
    @territories["US"] = "Sambandsríki Amerika"
    @territories["UY"] = "Uruguei"
    @territories["UZ"] = "Usbekistan"
    @territories["VA"] = "Vatikan"
    @territories["VC"] = "Saint Vinsent og Grenadinoyggjar"
    @territories["VE"] = "Venesuela"
    @territories["WS"] = "Sámoa"
    @territories["YE"] = "Jemen"
    @territories["ZA"] = "Suðurafrika"
    @territories["ZM"] = "Sambia"
    @territories["ZW"] = "Simbabvi"
    @scripts = {}
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[a-záæíðóøúý]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
