#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/sh_YU.xml
# Original file revision: 1.27 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @symbol_decimal = ","
    @symbol_group = "."
    @symbol_list = ";"
    @symbol_percentsign = "%"
    @symbol_nativezerodigit = "0"
    @symbol_patterndigit = "#"
    @symbol_plussign = "+"
    @symbol_minussign = "-"
    @symbol_exponential = "E"
    @symbol_permille = "‰"
    @symbol_infinity = "∞"
    @symbol_nan = "�"
    @decimalformat = "#,##0.###"
    @scientificformat = "#E0"
    @percentformat = "#,##0%"
  end

  public
  attr_reader :symbol_decimal
  attr_reader :symbol_group
  attr_reader :symbol_list
  attr_reader :symbol_percentsign
  attr_reader :symbol_nativezerodigit
  attr_reader :symbol_patterndigit
  attr_reader :symbol_plussign
  attr_reader :symbol_minussign
  attr_reader :symbol_exponential
  attr_reader :symbol_permille
  attr_reader :symbol_infinity
  attr_reader :symbol_nan
  attr_reader :decimalformat
  attr_reader :scientificformat
  attr_reader :percentformat
