#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/pt_BR.xml
# Original file revision: 1.28 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Casablanca"] = "Casablanca"
    @exemplarcities["America/Araguaina"] = "Araguaína"
    @exemplarcities["America/Argentina/Tucuman"] = "Tucumán"
    @exemplarcities["America/Belem"] = "Belém"
    @exemplarcities["America/Cancun"] = "Cancún"
    @exemplarcities["America/Cordoba"] = "Córdoba"
    @exemplarcities["America/Cuiaba"] = "Cuiabá"
    @exemplarcities["America/Guayaquil"] = "Guaiaquil"
    @exemplarcities["America/Indianapolis"] = "Indianápolis"
    @exemplarcities["America/Maceio"] = "Maceió"
    @exemplarcities["America/Merida"] = "Mérida"
    @exemplarcities["America/Mexico_City"] = "Cidade do México"
    @exemplarcities["America/New_York"] = "Nova Iorque"
    @exemplarcities["America/North_Dakota/Center"] = "Central"
    @exemplarcities["America/Sao_Paulo"] = "São Paulo"
    @exemplarcities["America/St_Johns"] = "St. Johns"
    @exemplarcities["Antarctica/South_Pole"] = "Pólo Sul"
    @exemplarcities["Asia/Jakarta"] = "Jacarta"
    @exemplarcities["Asia/Jerusalem"] = "Jerusalém"
    @exemplarcities["Asia/Shanghai"] = "Xangai"
    @exemplarcities["Asia/Tokyo"] = "Tóquio"
    @exemplarcities["Atlantic/Azores"] = "Açores"
    @exemplarcities["Atlantic/Canary"] = "Canárias"
    @exemplarcities["Europe/Bucharest"] = "Bucareste"
    @exemplarcities["Europe/Lisbon"] = "Lisboa"
    @exemplarcities["Europe/London"] = "Londres"
    @exemplarcities["Europe/Madrid"] = "Madri"
    @exemplarcities["Europe/Moscow"] = "Moscou"
    @exemplarcities["Europe/Paris"] = "Paris"
    @exemplarcities["Pacific/Galapagos"] = "Galápagos"
    @exemplarcities["Pacific/Tahiti"] = "Taiti"
    @long_generics = {}
    @long_standards = {}
    @long_standards["Africa/Casablanca"] = "Horário do Meridiano de Greenwich"
    @long_standards["America/Anchorage"] = "Horário Padrão do Alasca"
    @long_standards["America/Chicago"] = "Horário Padrão Central"
    @long_standards["America/Denver"] = "Horário Padrão Montanha"
    @long_standards["America/Halifax"] = "Horário Padrão Atlântico"
    @long_standards["America/Indianapolis"] = "Horário Padrão Oriental"
    @long_standards["America/Los_Angeles"] = "Horário Padrão do Pacífico"
    @long_standards["America/New_York"] = "Horário Padrão Oriental"
    @long_standards["America/Phoenix"] = "Horário Padrão Montanha"
    @long_standards["America/St_Johns"] = "Horário Padrão de Terra Nova"
    @long_standards["Asia/Jerusalem"] = "Horário Padrão de Israel"
    @long_standards["Asia/Shanghai"] = "Horário Padrão da China"
    @long_standards["Asia/Tokyo"] = "Horário Padrão do Japão"
    @long_standards["Europe/Bucharest"] = "Horário Padrão da Europa Oriental"
    @long_standards["Europe/Paris"] = "Horário Padrão Europa Central"
    @long_standards["Pacific/Honolulu"] = "Horário Padrão do Havaí"
    @long_daylights = {}
    @long_daylights["Africa/Casablanca"] = "Horário do Meridiano de Greenwich"
    @long_daylights["America/Anchorage"] = "Horário de Verão do Alasca"
    @long_daylights["America/Chicago"] = "Horário de Verão Central"
    @long_daylights["America/Denver"] = "Horário de Verão Montanha"
    @long_daylights["America/Halifax"] = "Horário de Verão Atlântico"
    @long_daylights["America/Indianapolis"] = "Horário Padrão Oriental"
    @long_daylights["America/Los_Angeles"] = "Horário de Verão do Pacífico"
    @long_daylights["America/New_York"] = "Horário de Verão Oriental"
    @long_daylights["America/Phoenix"] = "Horário Padrão Montanha"
    @long_daylights["America/St_Johns"] = "Horário de Verão de Terra Nova"
    @long_daylights["Asia/Jerusalem"] = "Horário de Verão de Israel"
    @long_daylights["Asia/Shanghai"] = "Horário Padrão da China"
    @long_daylights["Asia/Tokyo"] = "Horário Padrão do Japão"
    @long_daylights["Europe/Bucharest"] = "Horário de Verão da Europa Oriental"
    @long_daylights["Europe/Paris"] = "Horário de Verão Europa Central"
    @long_daylights["Pacific/Honolulu"] = "Horário Padrão do Havaí"
    @short_generics = {}
    @short_standards = {}
    @short_standards["Africa/Casablanca"] = "GMT"
    @short_standards["America/Anchorage"] = "AST"
    @short_standards["America/Chicago"] = "CST"
    @short_standards["America/Denver"] = "MST"
    @short_standards["America/Halifax"] = "AST"
    @short_standards["America/Indianapolis"] = "EST"
    @short_standards["America/Los_Angeles"] = "PST"
    @short_standards["America/New_York"] = "EST"
    @short_standards["America/Phoenix"] = "MST"
    @short_standards["America/St_Johns"] = "CNT"
    @short_standards["Asia/Jerusalem"] = "IST"
    @short_standards["Asia/Shanghai"] = "CTT"
    @short_standards["Asia/Tokyo"] = "JST"
    @short_standards["Europe/Bucharest"] = "EET"
    @short_standards["Europe/Paris"] = "CET"
    @short_standards["Pacific/Honolulu"] = "HST"
    @short_daylights = {}
    @short_daylights["Africa/Casablanca"] = "GMT"
    @short_daylights["America/Anchorage"] = "ADT"
    @short_daylights["America/Chicago"] = "CDT"
    @short_daylights["America/Denver"] = "MDT"
    @short_daylights["America/Halifax"] = "ADT"
    @short_daylights["America/Indianapolis"] = "EST"
    @short_daylights["America/Los_Angeles"] = "PDT"
    @short_daylights["America/New_York"] = "EDT"
    @short_daylights["America/Phoenix"] = "MST"
    @short_daylights["America/St_Johns"] = "CDT"
    @short_daylights["Asia/Jerusalem"] = "IDT"
    @short_daylights["Asia/Shanghai"] = "CDT"
    @short_daylights["Asia/Tokyo"] = "JST"
    @short_daylights["Europe/Bucharest"] = "EEST"
    @short_daylights["Europe/Paris"] = "CEST"
    @short_daylights["Pacific/Honolulu"] = "HST"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
