#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/is.xml
# Original file revision: 1.43 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["America/Buenos_Aires"] = "Búenos Aíres"
    @exemplarcities["America/Cancun"] = "Kankún"
    @exemplarcities["America/Mexico_City"] = "Mexíkóborg"
    @exemplarcities["America/Regina"] = "Regína"
    @exemplarcities["America/Santiago"] = "Santíagó"
    @exemplarcities["Antarctica/South_Pole"] = "Suðurpóll"
    @exemplarcities["Asia/Kuala_Lumpur"] = "Kúala Lúmpúr"
    @exemplarcities["Atlantic/Azores"] = "Asoreyjar"
    @exemplarcities["Atlantic/Canary"] = "Kanarí"
    @exemplarcities["Europe/Lisbon"] = "Lissabon"
    @exemplarcities["Europe/Madrid"] = "Madríd"
    @exemplarcities["Europe/Moscow"] = "Moskva"
    @exemplarcities["Pacific/Tahiti"] = "Tahítí"
    @long_generics = {}
    @long_standards = {}
    @long_daylights = {}
    @short_generics = {}
    @short_standards = {}
    @short_daylights = {}
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
