#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/kn.xml
# Original file revision: 1.31 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["kn"] = "ಕನ್ನಡ"
    @territories = {}
    @territories["AU"] = "ಆಸ್ಟ್ರೆಲಿಯ"
    @territories["CN"] = "ಚೀನ"
    @territories["EE"] = "ಎಸ್ತೊನಿಯ"
    @territories["IN"] = "ಭಾರತ"
    @territories["MV"] = "ಮಾಲ್ಡಿವ ದ್ವೀಪಗಳು"
    @territories["NP"] = "ನೆಪಾಳ"
    @territories["SG"] = "ಸಿಂಗಪುರ"
    @territories["TR"] = "ತುರ್ಕಿ"
    @scripts = {}
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[ಂಃಅ-ಌಎ-ಐಒ-ನಪ-ಳವ-ಹ಼-ೄೆ-ೈೊ-್ೕೖೞೠೡ೦-೯]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "ಹೌದು"
    @nostr = "ಇಲ್ಲ:ಅಲ್ಲ"
    @yesexpr = "^([yY]([eE][sS])?)|ಹೌದು"
    @noexpr = "^([nN][oO]?)|([ಇಅ]ಲ್ಲ)"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
