#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/pl.xml
# Original file revision: 1.51 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Kinshasa"] = "Kinszasa"
    @exemplarcities["Africa/Lubumbashi"] = "Lubumbaszi"
    @exemplarcities["America/Argentina/ComodRivadavia"] = "Comodoro Rivadavia"
    @exemplarcities["America/Mexico_City"] = "Meksyk"
    @exemplarcities["America/New_York"] = "Nowy Jork"
    @exemplarcities["America/St_Johns"] = "St. John's"
    @exemplarcities["Antarctica/DumontDUrville"] = "Dumont d'Urville"
    @exemplarcities["Antarctica/Mawson"] = "Wybrzeże Mawsona"
    @exemplarcities["Antarctica/McMurdo"] = "Mc Murdo"
    @exemplarcities["Antarctica/Palmer"] = "Archipelag Palmera"
    @exemplarcities["Antarctica/Rothera"] = "Stacja Naukowa Rothera"
    @exemplarcities["Antarctica/South_Pole"] = "Biegun południowy"
    @exemplarcities["Antarctica/Syowa"] = "Stacja Syowa"
    @exemplarcities["Antarctica/Vostok"] = "Wostok"
    @exemplarcities["Asia/Almaty"] = "Ałma Ata"
    @exemplarcities["Asia/Aqtau"] = "Aktau"
    @exemplarcities["Asia/Aqtobe"] = "Aktiubińsk"
    @exemplarcities["Asia/Choibalsan"] = "Czojbalsan"
    @exemplarcities["Asia/Chongqing"] = "Czunking"
    @exemplarcities["Asia/Hovd"] = "Howd"
    @exemplarcities["Asia/Irkutsk"] = "Irkuck"
    @exemplarcities["Asia/Jakarta"] = "Dżakarta"
    @exemplarcities["Asia/Kamchatka"] = "Kamczatka"
    @exemplarcities["Asia/Kashgar"] = "Kaszgar"
    @exemplarcities["Asia/Krasnoyarsk"] = "Krasnojarsk"
    @exemplarcities["Asia/Kuching"] = "Kuczing"
    @exemplarcities["Asia/Novosibirsk"] = "Nowosybirsk"
    @exemplarcities["Asia/Oral"] = "Uralsk"
    @exemplarcities["Asia/Qyzylorda"] = "Kyzył Orda"
    @exemplarcities["Asia/Sakhalin"] = "Sachalin"
    @exemplarcities["Asia/Samarkand"] = "Samarkanda"
    @exemplarcities["Asia/Shanghai"] = "Szanghaj"
    @exemplarcities["Asia/Tashkent"] = "Taszkient"
    @exemplarcities["Asia/Ulaanbaatar"] = "Ułan Bator"
    @exemplarcities["Asia/Urumqi"] = "Urumczi"
    @exemplarcities["Asia/Vladivostok"] = "Władywostok"
    @exemplarcities["Asia/Yakutsk"] = "Jakuck"
    @exemplarcities["Asia/Yekaterinburg"] = "Jekaterynburg"
    @exemplarcities["Atlantic/Azores"] = "Azory"
    @exemplarcities["Atlantic/Canary"] = "Wyspy Kanaryjskie"
    @exemplarcities["Atlantic/Madeira"] = "Madera"
    @exemplarcities["Australia/Lord_Howe"] = "Wyspa Lord Howe"
    @exemplarcities["Europe/Kiev"] = "Kijów"
    @exemplarcities["Europe/Lisbon"] = "Lizbona"
    @exemplarcities["Europe/London"] = "Londyn"
    @exemplarcities["Europe/Madrid"] = "Madryt"
    @exemplarcities["Europe/Moscow"] = "Moskwa"
    @exemplarcities["Europe/Simferopol"] = "Symferopol"
    @exemplarcities["Europe/Uzhgorod"] = "Użgorod"
    @exemplarcities["Europe/Zaporozhye"] = "Zaporoże"
    @exemplarcities["Pacific/Easter"] = "Wyspy Wielkanocne"
    @long_generics = {}
    @long_standards = {}
    @long_daylights = {}
    @short_generics = {}
    @short_standards = {}
    @short_daylights = {}
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
