#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/cs.xml
# Original file revision: 1.60 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Casablanca"] = "Casablanca"
    @exemplarcities["America/Cordoba"] = "Kordoba"
    @exemplarcities["America/Tijuana"] = "Tichuana"
    @exemplarcities["Antarctica/South_Pole"] = "Jižní pól"
    @exemplarcities["Asia/Jakarta"] = "Jakarta"
    @exemplarcities["Asia/Jerusalem"] = "Jeruzalém"
    @exemplarcities["Asia/Kamchatka"] = "Kamčatka"
    @exemplarcities["Asia/Kashgar"] = "Kašghar"
    @exemplarcities["Asia/Krasnoyarsk"] = "Krasnojarsk"
    @exemplarcities["Asia/Sakhalin"] = "Sachalin"
    @exemplarcities["Asia/Tashkent"] = "Taškent"
    @exemplarcities["Asia/Tokyo"] = "Tokio"
    @exemplarcities["Asia/Ulaanbaatar"] = "Ulánbátar"
    @exemplarcities["Asia/Yakutsk"] = "Jakutsk"
    @exemplarcities["Asia/Yekaterinburg"] = "Jekatěrinburg"
    @exemplarcities["Atlantic/Azores"] = "Azorské ostrovy"
    @exemplarcities["Atlantic/Canary"] = "Kanárské ostrovy"
    @exemplarcities["Europe/Bucharest"] = "Bukurešť"
    @exemplarcities["Europe/Kiev"] = "Kyjev"
    @exemplarcities["Europe/Lisbon"] = "Lisabon"
    @exemplarcities["Europe/London"] = "Londýn"
    @exemplarcities["Europe/Moscow"] = "Moskva"
    @exemplarcities["Europe/Paris"] = "Paříž"
    @exemplarcities["Europe/Uzhgorod"] = "Užhorod"
    @exemplarcities["Europe/Zaporozhye"] = "Záporoží"
    @exemplarcities["Pacific/Galapagos"] = "Galapágy"
    @long_generics = {}
    @long_standards = {}
    @long_standards["Africa/Casablanca"] = "Greenwichský střední čas"
    @long_standards["America/Anchorage"] = "Aljašský standardní čas"
    @long_standards["America/Chicago"] = "Centrální standardní čas"
    @long_standards["America/Denver"] = "Horský standardní čas"
    @long_standards["America/Halifax"] = "Atlantický standardní čas"
    @long_standards["America/Indianapolis"] = "Východní standardní čas"
    @long_standards["America/Los_Angeles"] = "Pacifický standardní čas"
    @long_standards["America/New_York"] = "Východní standardní čas"
    @long_standards["America/Phoenix"] = "Horský standardní čas"
    @long_standards["Asia/Jerusalem"] = "Izraelský standardní čas"
    @long_standards["Asia/Tokyo"] = "Japonský standardní čas"
    @long_standards["Europe/Bucharest"] = "Východoevropský standardní čas"
    @long_standards["Europe/Paris"] = "Středoevropský standardní čas"
    @long_standards["Pacific/Honolulu"] = "Havajský standardní čas"
    @long_daylights = {}
    @long_daylights["Africa/Casablanca"] = "Greenwichský střední čas"
    @long_daylights["America/Anchorage"] = "Aljašský letní čas"
    @long_daylights["America/Chicago"] = "Centrální letní čas"
    @long_daylights["America/Denver"] = "Horský letní čas"
    @long_daylights["America/Halifax"] = "Atlantický letní čas"
    @long_daylights["America/Indianapolis"] = "Východní letní čas"
    @long_daylights["America/Los_Angeles"] = "Pacifický letní čas"
    @long_daylights["America/New_York"] = "Východní letní čas"
    @long_daylights["America/Phoenix"] = "Horský letní čas"
    @long_daylights["Asia/Jerusalem"] = "Izraelský letní čas"
    @long_daylights["Asia/Tokyo"] = "Japonský letní čas"
    @long_daylights["Europe/Bucharest"] = "Východoevropský letní čas"
    @long_daylights["Europe/Paris"] = "Středoevropský letní čas"
    @long_daylights["Pacific/Honolulu"] = "Havajský letní čas"
    @short_generics = {}
    @short_standards = {}
    @short_standards["Africa/Casablanca"] = "GMT"
    @short_standards["America/Anchorage"] = "AST"
    @short_standards["America/Chicago"] = "CST"
    @short_standards["America/Denver"] = "MST"
    @short_standards["America/Halifax"] = "AST"
    @short_standards["America/Indianapolis"] = "EST"
    @short_standards["America/Los_Angeles"] = "PST"
    @short_standards["America/New_York"] = "EST"
    @short_standards["America/Phoenix"] = "MST"
    @short_standards["Asia/Jerusalem"] = "IST"
    @short_standards["Asia/Tokyo"] = "JST"
    @short_standards["Europe/Bucharest"] = "EET"
    @short_standards["Europe/Paris"] = "CET"
    @short_standards["Pacific/Honolulu"] = "HST"
    @short_daylights = {}
    @short_daylights["Africa/Casablanca"] = "GMT"
    @short_daylights["America/Anchorage"] = "ADT"
    @short_daylights["America/Chicago"] = "CDT"
    @short_daylights["America/Denver"] = "MDT"
    @short_daylights["America/Halifax"] = "ADT"
    @short_daylights["America/Indianapolis"] = "EST"
    @short_daylights["America/Los_Angeles"] = "PDT"
    @short_daylights["America/New_York"] = "EDT"
    @short_daylights["America/Phoenix"] = "MST"
    @short_daylights["Asia/Jerusalem"] = "IDT"
    @short_daylights["Asia/Tokyo"] = "JST"
    @short_daylights["Europe/Bucharest"] = "EEST"
    @short_daylights["Europe/Paris"] = "CEST"
    @short_daylights["Pacific/Honolulu"] = "HST"
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
