#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/so_SO.xml
# Original file revision: 1.29 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @languages = {}
    @languages["ar"] = "Arabic"
    @languages["de"] = "German"
    @languages["en"] = "English"
    @languages["es"] = "Spanish"
    @languages["fr"] = "French"
    @languages["hi"] = "Hindi"
    @languages["it"] = "Italian"
    @languages["ja"] = "Japanese"
    @languages["pt"] = "Portuguese"
    @languages["ru"] = "Russian"
    @languages["so"] = "Soomaali"
    @languages["zh"] = "Chinese"
    @territories = {}
    @territories["AE"] = "Imaaraadka Carabta ee Midoobay"
    @territories["AF"] = "Afgaanistaan"
    @territories["AM"] = "Armeeniya"
    @territories["AO"] = "Angoola"
    @territories["AT"] = "Osteeriya"
    @territories["AU"] = "Awstraaliya"
    @territories["BA"] = "Boosniya Heersigoviina"
    @territories["BB"] = "Baarbadoos"
    @territories["BD"] = "Bangaala-Deesh"
    @territories["BE"] = "Beljiyam"
    @territories["BH"] = "Baxrayn"
    @territories["BJ"] = "Beniin"
    @territories["BR"] = "Braasiil"
    @territories["CA"] = "Kanada"
    @territories["CH"] = "Swiiserlaand"
    @territories["CL"] = "Jili"
    @territories["CM"] = "Kameruun"
    @territories["CN"] = "Shiinaha"
    @territories["CU"] = "Kuuba"
    @territories["DE"] = "Jarmal"
    @territories["DJ"] = "Jabuuti"
    @territories["DK"] = "Danmaark"
    @territories["EG"] = "Masar"
    @territories["ES"] = "Isbeyn"
    @territories["ET"] = "Itoobiya"
    @territories["FI"] = "Fiinlaand"
    @territories["FR"] = "Faransiis"
    @territories["GB"] = "United Kingdom"
    @territories["GD"] = "Giriinaada"
    @territories["GN"] = "Gini"
    @territories["GR"] = "Giriigga"
    @territories["HR"] = "Korweeshiya"
    @territories["HU"] = "Hangeri"
    @territories["ID"] = "Indoneesiya"
    @territories["IE"] = "Ayrlaanda"
    @territories["IL"] = "Israaʼiil"
    @territories["IN"] = "Hindiya"
    @territories["IQ"] = "Ciraaq"
    @territories["IR"] = "Iiraan"
    @territories["IS"] = "Iislaand"
    @territories["IT"] = "Talyaani"
    @territories["JM"] = "Jameyka"
    @territories["JO"] = "Urdun"
    @territories["JP"] = "Jabbaan"
    @territories["KE"] = "Kiiniya"
    @territories["KH"] = "Kamboodiya"
    @territories["KP"] = "Kuuriyada Waqooyi"
    @territories["KR"] = "Kuuriyada Koonfureed"
    @territories["KW"] = "Kuwayt"
    @territories["KZ"] = "Kasaakhistaan"
    @territories["LB"] = "Lubnaan"
    @territories["LK"] = "Siirilaanka"
    @territories["LR"] = "Laybeeriya"
    @territories["LS"] = "Losooto"
    @territories["LU"] = "Luksemboorg"
    @territories["LV"] = "Laatfiya"
    @territories["LY"] = "Liibiya"
    @territories["MA"] = "Marooko"
    @territories["MC"] = "Moonako"
    @territories["MK"] = "Makadooniya"
    @territories["ML"] = "Maali"
    @territories["MR"] = "Muritaaniya"
    @territories["MT"] = "Maalda"
    @territories["MV"] = "Maaldiqeen"
    @territories["MW"] = "Malaawi"
    @territories["MX"] = "Meksiko"
    @territories["MZ"] = "Musambiig"
    @territories["NA"] = "Namiibiya"
    @territories["NG"] = "Nayjeeriya"
    @territories["NI"] = "Nikaraaguwa"
    @territories["NO"] = "Noorweey"
    @territories["NZ"] = "Neyuusilaand"
    @territories["OM"] = "Cumaan"
    @territories["PH"] = "Filibiin"
    @territories["PK"] = "Bakistaan"
    @territories["PL"] = "Booland"
    @territories["PT"] = "Bortuqaal"
    @territories["QA"] = "Qadar"
    @territories["RO"] = "Rumaaniya"
    @territories["RU"] = "Ruush"
    @territories["SA"] = "Sacuudi Carabiya"
    @territories["SD"] = "Sudaan"
    @territories["SE"] = "Iswidhan"
    @territories["SL"] = "Siraaliyoon"
    @territories["SO"] = "Soomaaliya"
    @territories["SY"] = "Suuriya"
    @territories["TD"] = "Jaad"
    @territories["TG"] = "Toogo"
    @territories["TH"] = "Taylaand"
    @territories["TN"] = "Tuniisiya"
    @territories["TR"] = "Turki"
    @territories["TZ"] = "Tansaaniya"
    @territories["UG"] = "Ugaanda"
    @territories["US"] = "Qaramada Midoobey ee Maraykanka"
    @territories["VA"] = "Faatikaan"
    @territories["VE"] = "Fenisuweela"
    @territories["VN"] = "Fiyetnaam"
    @territories["YE"] = "Yaman"
    @territories["ZA"] = "Koonfur Afrika"
    @territories["ZM"] = "Saambiya"
    @territories["ZW"] = "Simbaabwe"
    @scripts = {}
    @scripts["Latn"] = "Latin"
    @character_exemplar_characters = {}
    @character_exemplar_characters["default"] = "[a-z]"
    @character_exemplar_characters["auxiliary"] = "[]"
    @delimiter_quotation_start = "“"
    @delimiter_quotation_end = "”"
    @delimiter_alternate_quotation_start = "‘"
    @delimiter_alternate_quotation_end = "’"
    @measurement_system = "metric"
    @measurement_papersize_height = "297"
    @measurement_papersize_width = "210"
    @variants = {}
    @keys = {}
    @types = {}
    @yesstr = "yes:y"
    @nostr = "no:n"
    @yesexpr = "^[yY]([eE][sS])?"
    @noexpr = "^[nN][oO]?"
    @references = {}
  end

  public
  attr_reader :languages
  attr_reader :territories
  attr_reader :scripts
  attr_reader :layout_orientation
  attr_reader :layout_inlist_casing
  attr_reader :character_exemplar_characters
  attr_reader :character_mapping
  attr_reader :delimiter_quotation_start
  attr_reader :delimiter_quotation_end
  attr_reader :delimiter_alternate_quotation_start
  attr_reader :delimiter_alternate_quotation_end
  attr_reader :measurement_system
  attr_reader :measurement_papersize_height
  attr_reader :measurement_papersize_width
  attr_reader :variants
  attr_reader :keys
  attr_reader :types
  attr_reader :yesstr
  attr_reader :nostr
  attr_reader :yesexpr
  attr_reader :noexpr
  attr_reader :references
