#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/tr_TR.xml
# Original file revision: 1.28 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @hourformat = "+HH:mm;-HH:mm"
    @hoursformat = "{0}/{1}"
    @regionformat = "{0}"
    @fallbackformat = "{0} ({1})"
    @abbreviationfallback = "standard"
    @preferenceordering = ""
    @singlecountries = "Africa/Bamako America/Godthab America/Santiago America/Guayaquil     Asia/Shanghai Asia/Tashkent Asia/Kuala_Lumpur     Europe/Madrid Europe/Lisbon Europe/London Pacific/Auckland Pacific/Tahiti"
    @exemplarcities = {}
    @exemplarcities["Africa/Ceuta"] = "Septe"
    @exemplarcities["Africa/Kinshasa"] = "Kinşasa"
    @exemplarcities["Africa/Lubumbashi"] = "Lubumbaşi"
    @exemplarcities["America/Cancun"] = "Kankun"
    @exemplarcities["America/Chicago"] = "Şikago"
    @exemplarcities["America/Mexico_City"] = "Meksiko City"
    @exemplarcities["Antarctica/South_Pole"] = "Güney Kutbu"
    @exemplarcities["Asia/Almaty"] = "Almatı"
    @exemplarcities["Asia/Aqtau"] = "Şevçenko"
    @exemplarcities["Asia/Aqtobe"] = "Aktyubinsk"
    @exemplarcities["Asia/Choibalsan"] = "Çoybalsan"
    @exemplarcities["Asia/Chongqing"] = "Çunking"
    @exemplarcities["Asia/Hovd"] = "Kobdo"
    @exemplarcities["Asia/Jakarta"] = "Cakarta"
    @exemplarcities["Asia/Kamchatka"] = "Kamçatka"
    @exemplarcities["Asia/Kashgar"] = "Kaşgar"
    @exemplarcities["Asia/Kuching"] = "Kuçing"
    @exemplarcities["Asia/Oral"] = "Uralsk"
    @exemplarcities["Asia/Qyzylorda"] = "Kızıl-Orda"
    @exemplarcities["Asia/Samarkand"] = "Semerkand"
    @exemplarcities["Asia/Shanghai"] = "Şangay"
    @exemplarcities["Asia/Tashkent"] = "Taşkent"
    @exemplarcities["Asia/Ulaanbaatar"] = "Ulanbator"
    @exemplarcities["Asia/Urumqi"] = "Urumçi"
    @exemplarcities["Atlantic/Azores"] = "Azor Adaları"
    @exemplarcities["Atlantic/Canary"] = "Kanarya"
    @exemplarcities["Australia/Melbourne"] = "Melborn"
    @exemplarcities["Australia/Sydney"] = "Sidney"
    @exemplarcities["Europe/Lisbon"] = "Lizbon"
    @exemplarcities["Europe/London"] = "Londra"
    @exemplarcities["Europe/Moscow"] = "Moskova"
    @exemplarcities["Pacific/Marquesas"] = "Markiz"
    @long_generics = {}
    @long_standards = {}
    @long_standards["America/Anchorage"] = "Alaska Standart Saati"
    @long_standards["America/Chicago"] = "Merkezi Standart Saati"
    @long_standards["America/Denver"] = "ABD Sıradağlar Standart Saati"
    @long_standards["America/Halifax"] = "Atlantik Standart Saati"
    @long_standards["America/Indianapolis"] = "Doğu Standart Saati"
    @long_standards["America/Los_Angeles"] = "Pasifik Standart Saati"
    @long_standards["America/New_York"] = "Doğu Standart Saati"
    @long_standards["America/Phoenix"] = "ABD Sıradağlar Standart Saati"
    @long_standards["America/St_Johns"] = "Newfoundland Standart Saati"
    @long_standards["Asia/Shanghai"] = "Çin Standart Saati"
    @long_standards["Pacific/Honolulu"] = "Hawaii Standart Saati"
    @long_daylights = {}
    @long_daylights["America/Anchorage"] = "Alaska Yaz Saati"
    @long_daylights["America/Chicago"] = "Merkezi Yaz Saati"
    @long_daylights["America/Denver"] = "ABD Sıradağlar Yaz Saati"
    @long_daylights["America/Halifax"] = "Atlantik Yaz Saati"
    @long_daylights["America/Indianapolis"] = "Doğu Standart Saati"
    @long_daylights["America/Los_Angeles"] = "Pasifik Yaz Saati"
    @long_daylights["America/New_York"] = "Doğu Yaz Saati"
    @long_daylights["America/Phoenix"] = "ABD Sıradağlar Standart Saati"
    @long_daylights["America/St_Johns"] = "Newfoundland Yaz Saati"
    @long_daylights["Asia/Shanghai"] = "Çin Standart Saati"
    @long_daylights["Pacific/Honolulu"] = "Hawaii Standart Saati"
    @short_generics = {}
    @short_standards = {}
    @short_daylights = {}
  end

  public
  attr_reader :hourformat
  attr_reader :hoursformat
  attr_reader :regionformat
  attr_reader :fallbackformat
  attr_reader :abbreviationfallback
  attr_reader :preferenceordering
  attr_reader :singlecountries
  attr_reader :exemplarcities
  attr_reader :long_generics
  attr_reader :long_standards
  attr_reader :long_daylights
  attr_reader :short_generics
  attr_reader :short_standards
  attr_reader :short_daylights
