#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/ca.xml
# Original file revision: 1.47 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @format = "¤ #,##0.00"
    @before_match = "[:letter:]"
    @before_match_surrounding = "[:digit:]"
    @before_insertbetween = " "
    @after_match = "[:letter:]"
    @after_match_surrounding = "[:digit:]"
    @after_insertbetween = " "
    @currencies = {}
    @currencies["BRL"] = "Real brasiler"
    @currencies["CNY"] = "Iuan renmimbi xinès"
    @currencies["EUR"] = "Euro"
    @currencies["GBP"] = "Lliura esterlina britànica"
    @currencies["INR"] = "Rupia índia"
    @currencies["ITL"] = "ITL"
    @currencies["JPY"] = "Ien japonès"
    @currencies["RUB"] = "Ruble rus"
    @currencies["USD"] = "Dòlar EUA"
    @symbols = {}
    @symbols["ESP"] = "₧"
    @symbols["EUR"] = "€"
    @symbols["GBP"] = "£"
    @symbols["INR"] = "=0#Rs.|1#Re.|1<Rs."
    @symbols["ITL"] = "₤"
    @symbols["JPY"] = "¥"
    @symbols["USD"] = "$"
  end

  public
  attr_reader :format
  attr_reader :before_match
  attr_reader :before_match_surrounding
  attr_reader :before_insertbetween
  attr_reader :after_match
  attr_reader :after_match_surrounding
  attr_reader :after_insertbetween
  attr_reader :currencies
  attr_reader :symbols
