#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/fa.xml
# Original file revision: 1.43 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @format = "#,##0.00 ¤;'‪'-#,##0.00'‬' ¤"
    @before_match = "[:letter:]"
    @before_match_surrounding = "[:digit:]"
    @before_insertbetween = " "
    @after_match = "[:letter:]"
    @after_match_surrounding = "[:digit:]"
    @after_insertbetween = " "
    @currencies = {}
    @currencies["AED"] = "درهم امارات"
    @currencies["AFA"] = "افغانی قدیم"
    @currencies["AFN"] = "افغانی"
    @currencies["ATS"] = "شیلینگ اتریش"
    @currencies["AUD"] = "دلار استرالیا"
    @currencies["AZM"] = "منات جمهوری آذربایجان"
    @currencies["BHD"] = "دینار بحرین"
    @currencies["BIF"] = "فرانک بوروندی"
    @currencies["BND"] = "دلار برونئی"
    @currencies["BYR"] = "روبل بیلوروسی"
    @currencies["CAD"] = "دلار کانادا"
    @currencies["CHF"] = "فرانک سوئیس"
    @currencies["DEM"] = "مارک آلمان"
    @currencies["DKK"] = "کرون دانمارک"
    @currencies["EUR"] = "یورو"
    @currencies["FRF"] = "فرانک فرانسه"
    @currencies["GBP"] = "پوند استرلینگ بریتانیا"
    @currencies["HUF"] = "فورینت مجارستان"
    @currencies["INR"] = "روپیهٔ هند"
    @currencies["IQD"] = "دینار عراق"
    @currencies["IRR"] = "ریال ایران"
    @currencies["ITL"] = "ITL"
    @currencies["JOD"] = "دینار اردن"
    @currencies["JPY"] = "ین ژاپن"
    @currencies["KWD"] = "دینار کویت"
    @currencies["MXN"] = "پزوی مکزیک"
    @currencies["NLG"] = "گیلدر هلند"
    @currencies["NOK"] = "کرون نروژ"
    @currencies["OMR"] = "ریال عمان"
    @currencies["PKR"] = "روپیهٔ پاکستان"
    @currencies["QAR"] = "ریال قطر"
    @currencies["RUB"] = "روبل روسیه"
    @currencies["SAR"] = "ریال سعودی"
    @currencies["SEK"] = "کرون سوئد"
    @currencies["SGD"] = "دلار سنگاپور"
    @currencies["TJR"] = "روبل تاجیکستان"
    @currencies["TJS"] = "سامانی تاجیکستان"
    @currencies["TND"] = "دینار تونس"
    @currencies["TRL"] = "لیرهٔ ترکیه"
    @currencies["TRY"] = "لیرهٔ جدید ترکیه"
    @currencies["USD"] = "دلار امریکا"
    @currencies["XAG"] = "نقره"
    @currencies["XAU"] = "طلا"
    @currencies["XPD"] = "پالادیم"
    @currencies["XPT"] = "پلاتین"
    @currencies["YER"] = "ریال یمن"
    @symbols = {}
    @symbols["AFA"] = "افغانی"
    @symbols["AFN"] = "افغانی"
    @symbols["EUR"] = "€"
    @symbols["GBP"] = "£"
    @symbols["INR"] = "=0#Rs.|1#Re.|1<Rs."
    @symbols["IRR"] = "﷼"
    @symbols["ITL"] = "₤"
    @symbols["JPY"] = "¥"
    @symbols["USD"] = "$"
  end

  public
  attr_reader :format
  attr_reader :before_match
  attr_reader :before_match_surrounding
  attr_reader :before_insertbetween
  attr_reader :after_match
  attr_reader :after_match_surrounding
  attr_reader :after_insertbetween
  attr_reader :currencies
  attr_reader :symbols
