#
# a language data file for Ruby/CLDR
#
# Generated by: CLDR::Generator
#
# CLDR version: 1.3
#
# Original file name: common/main/te.xml
# Original file revision: 1.37 $
#
# Copyright (C) 2006 Masao Mutoh
#
# This file is distributed under the same license as the Ruby/CLDR.
#

  private
  def init_data
    @format = "¤ #,##0.00"
    @before_match = "[:letter:]"
    @before_match_surrounding = "[:digit:]"
    @before_insertbetween = " "
    @after_match = "[:letter:]"
    @after_match_surrounding = "[:digit:]"
    @after_insertbetween = " "
    @currencies = {}
    @currencies["BRL"] = "బ్రజిల్ దేశ రియాల్"
    @currencies["CNY"] = "చైనా  దేశ యువాన్ రెన్‌మిన్‌బి"
    @currencies["EUR"] = "యురొ"
    @currencies["GBP"] = "బ్ిటిష్ పౌన్డ స్టెర్లిగ్"
    @currencies["INR"] = "రూపాయి"
    @currencies["ITL"] = "ITL"
    @currencies["JPY"] = "జపాను దేశ యెస్"
    @currencies["RUB"] = "రష్య దేశ రూబల్"
    @currencies["USD"] = "ఐక్య రాష్ట్ర అమెరిక డాలర్"
    @symbols = {}
    @symbols["BRL"] = "రి$"
    @symbols["CNY"] = "యు"
    @symbols["EUR"] = "€"
    @symbols["GBP"] = "£"
    @symbols["INR"] = "రూ."
    @symbols["ITL"] = "₤"
    @symbols["JPY"] = "¥"
    @symbols["RUB"] = "రూబల్"
    @symbols["USD"] = "$"
  end

  public
  attr_reader :format
  attr_reader :before_match
  attr_reader :before_match_surrounding
  attr_reader :before_insertbetween
  attr_reader :after_match
  attr_reader :after_match_surrounding
  attr_reader :after_insertbetween
  attr_reader :currencies
  attr_reader :symbols
